apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stable-diffusion-runners
  namespace: arc-systems
spec:
  interval: 60m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
      interval: 12h
  values:
    githubConfigSecret: pre-defined-secret
    githubConfigUrl: https://github.com/Apoorva64/stable-diffusion-web-ui