apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: tailscale-maxime-operator
  namespace: tailscale-maxime-operator
spec:
  interval: 1h
  url: https://github.com/tailscale/tailscale