apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarqube-database
  namespace: sonarqube
spec:
  interval: 30m
  chart:
    spec:
      chart: postgresql
      version: "15.5.38"
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    global:
      postgresql:
        auth:
          username: sonarqube
          database: sonarqube
          existingSecret: sonarqube-database-password
          secretKeys:
            adminPasswordKey: postgresPassword
            userPasswordKey: password
            replicationPasswordKey: replicationPassword