---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auth-generic-oauth-secret
  namespace: monitoring
spec:
  encryptedData:
    client_id: AgASpaWIogepomQKtODOIKRPjzRpSe0GWok2HzEU2SDxOH+NR5VCFByzX4plOT3CcY4PcE2s1faMvYJ8nX5mu7+kezEyZO9b54VAorRUm/uyL75qkUztgFpazvgYDmK0+3XINLDpj9DkU3wN2feveriEHO43cd8WQjX+HqQJShulJ07D8rH397b3oO8b1BDn3GUbgF03yfAOp3wK2G/mwR8D9ZJwg0eYJ9mHkC5F1J7NCbvD11ZRCNO+/K7jwyYbTsXofi9hampti6J7NZtM+SSLGNIfLbMOXdSFZ7DxzKcteq0HrhhCVA7VCWmH0esM5oERi399G9hSiVhR1dRRgOiUwge1TAdC2iQWWQ0SHDB0AHMbikiRQ1lUY+KRNj4bJlgGe2TAtaVkGLLdIBgVB2vF5cPbxzbuVltr4w/al1Hm2VrXVDsq20YfcZELsX4XU5HcRWEvnqaeEaCxP965VS0lPijtz1pWNhik7GX9MaphHjXrDTNvk1vft1iL/cPt2OsV/zPZPA8oiBQCPMWUUeJ3FJ+iQW/PJj4M8a6Ci9c+1K7JuRuaVbtJl2yjElE0ANb0y2lTe2G3sKCQAdETckeOjmoVfxgksTNPmLO62+IUWOsVRmjzBBuWVxb9WLWDZdvn5wxWBiokQdNNIzOa5+p2/i7Lbsg6Al2U5ZFiFUODX7Z6bs3E8ia+fy9UjPpnMlU7RlfagNqnJ21rqC+S
    client_secret: AgBJvLOVpO2aB2v11+cpXPHzanlKW7IfbnR3wRT9nQsHjhRn9J5mT7kPCN2u/EGiDB+t0NudzhQKH2XDOPhfSeFyaGNAJIfvfBARaeBUoolFY7uE8DQ1mksIRnRvbnWoLeG3HldEdFblCU1g++OThJwJiEWsw2WPHXFPBp1aWMeJAlsZGlfTMeeAim88UR25IlgfeP8tIu3ucA/oMqvQ1OaAIvuXq9o+p6VAf4eEFXWjVr7/OKGlbNvIXS4Xtynrm1khb1jsEzdl1fbHYT6PJi0n0azHvjPNqHIdnsITGWrIQmS0YZ687TXMVbj5t/93sSg0zbaxjhe2MT1Y7Mp0xWcT4fT0fbVgOtmOOZiTfSmGF45HPv7+2tfZ9plHaIbJhyw6dChCMTa0V4zJVYL6cuij1Ha6g3zzCpenJrADXM89nzcYCmzopU1plx1HA0nPXD2Bf3rSPsAqEbIAYdYpvHtK4xIy/FEIsdG0WXerV1HWa/mYGVYmlBqv/i46gKl8VGzFydBcqJHonDfJ54os1dmvr4ORnVdPKxPT1faDBers9fR/OX0uz9sK3FGtcFdwI/toeWuSs/DUBGRqnFJY3Z2lTisn/zdhuQuZAkE0qhN460hAszolhEv3uZwwwRNFVUZab6rdXJBnmJOfiH5eAThM1ED/kK8g6pfCWSxPuUeMrtNAqRDTZDDZKj7vysGdAmVP89uL2tUDODNWfxSOAfdHHYqEJ8gdyt7tqs2V6GQ6AQ==
  template:
    metadata:
      creationTimestamp: null
      name: auth-generic-oauth-secret
      namespace: monitoring
