apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auth-generic-oauth-secret
  namespace: monitoring
spec:
  encryptedData:
    client_id: AgArTS97y7r6SRYrTPs2rtRdn10WAXa+pdNLfLy0oh8xUdDRWfhWloNbw2FkfYZLdmPXKT9DH4A4fCna8+YC2xXK6P+6dfJqbXuWxVvwg90umw79aZn74EU0L8IYdqcjM23j2DfqrlPDqmrrlvG1TrtQDQ8oZgqOFkoumBb8zvziQ5SgEX2kcJhCm1OLsKZgI/07da37TXyLj/FxiUQiFNMG0zEAiN/II1xfMYvFYLn77xcUdI4nPdqtovlDq2zYdKTIIoTFDqv1bQSHtG1NUmLEYXKM+HS+3mI6Y7zJ31QYYG8dsB99OH8OfbyONwkCJL46EykcOz6KJ/Cp3ALQoMDW/DSGSOzUEQqRF05YRU5wS5VCaUdYJOiBgdfmb557R0WsOd1SNx9pBgkUoaskFhn3xicdqcglpjI+dsihboqrR2/Gfc5IhWnxzl5g4cnGfiGRtfCgA31PsU4n+WhovvXe3cYMDdyhNWoBWOrH9FhLm9OGDSGlrG0m51hb5vociPF9MMw9t4eqWKORhjve6kLYCed+cZB+op2eyuBCiaHsD8eUjYv4UDdJEJ8KjFBgOa9/CH2c7nVCaPBZ6z/5gqkn7r+Uyyqul3m3Q5zTqFemAO/3rZ7nw8RWpFGPdhVAA80qrehJTzcguyoQ2kOae/xYUadhApuMQa5Hx/R/4vxuhLahDvXgCQH0VpLbDHW8/WcE/Vp2UIsJouDCMLfm
    client_secret: AgCkznLscZmEuc1x5REarpuAwjFG2qFZddZ08BhYE9G7kUDFTG0Q3yKJwW2tp6X14LF+9RuG/lS/KOSARjVqQbNdfOGwxDjMqEjZ9S9icy/f3SBCms3Ib6C07xJv/um+o6ruDzD0JCfeWIRF5ls63m9sEg+Qh1YYwnRilyIKPeFsW3eH15j0DNCHCOFzNus/UElam1XPnoFrlWHmh3hkPoSGfwAvo0HaD72vlXF5Uk3D8lEOt4t2e5u0vp2GSzI7pAxe7g/y6qvagoIsjfpMNiV4HQ1neJ7/GkiLSHyGYnm5QIBmSI62BGvAGyK9sv3dtmeqNTMuMq5wybrpts9rCXjM3oJse3vRzersKPxmjFD1Mk/GYJPDf8PduUvpGdPzM9ZzT36Yf3LxcqmdqS4OZq4yg9Zs5HmXMLDmG6032ETC4fwhtQft64Cy9Z1ICN/umSK0OqiLozEn+82hxeYu3S/5zdcAMbyZvrd9QFk+wiDIwwajk0JokMxuLFABmhz545v8Zdilgejshus9kqb9+GKLaK0hXa0Hb7OaKgm/sgXq5mKi9I2EXZW/dVfwHarRDSrQru50QhYO3hg3jKIMqgSIVpgbcrBp03SMcI/Ajnf9Z0XG9cDUYwAEZ1wzilOCDw+OzO7aR7d/sj5czR59G7MQDoFYztwdhMiSr2NJBRkwxr70ERYWNK+507AG9ROqUOi3eLSP4R1fc/asE37YFfmYpAmM6bBS8RNPkjjrXr/bKA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: auth-generic-oauth-secret
      namespace: monitoring

