---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auth-generic-oauth-secret
  namespace: monitoring
spec:
  encryptedData:
    client_id: AgAoR7lrtcGG5H/6kvKrYfnoZNoBKMkgZpXczqB+8zMxvRO3EefCcIrM+5SW7S2V/D4pxH1/pUDOp7lUB9oPEhM8ePEVwMhyenuq/qeLLrmkqGYsKNg88k3Pr7b99aqUCbLRyxSFZRlFeNtIleCONntAiVry2p78ulOBpkR1uIjiz86nE4HtJqARChed0aw2+vHbuHBa+9kjqJAMwozMTNZ+sy02s68Uvye2UQlHf+l06iGGpwgqm4lnNRRFSZR2EtzC0DTi3QHkjbmW5w/6XV7jjk+nHMEThU7F6A35uxZWqZiAQVwGmcBvnRMlWvJ0jg+M0J6/AIC03Vc1WJc0UW5KzeFLLlCQ+farI5mU/dqgip9Cs7ktYn+rbwciXos+0eQdUKG6KiQYp2um2ISjLPo9vV5qoQl/c1jmMtTfgsfhD4YJ/FhXO5pw3kfyEQhhQadW94u4eiNgzlOC6v9NNtBwnVn3FYof2IuoBpB7bftPML3MCSVzlpc/cWPyy7146SZJlCKxOw3GMreCXZ9w0n95x6uX2Ns8xAZ95w0CHZobu7jjQTcaSYQjsmykjYY+6wHz51hQbvnJ567eNxcDAa+w+HNfhf4k51GlzFwTeeYEbdVgRVWQafIYmSKajQgypllaRogUSt8ov4F1efPyfYt5VTFz5sUKpM2nM5PxrO/5zgYG7ob8fw/+dutMUkMRr8Z2P9XBLXyUwkim68Lj
    client_secret: AgASN1Z3/0xdtzop74tneyMo+rdssh2eHuju54yidFwoIlOO/jL+D5IdNMPbAOYg0RFFrRhu1t1WPgGVW2Yl8eYpt7idKJ+G2xO/VtCPLHhBDfJvSvt5X2MZvEErOwFHQe4IKCV33ylKi2TsctS4YMyuATBy9bSHKIL5Hh0t51ITC2OjHap0HFXQ6EWuum+y2t1NmKgJU9AQ/eLD3Uj9s+lLi3fHkG6nhVgOZqcWOsV/CNhZAfZ+5WTJFMUNOJDXpf7J5hXZen5Dt4sC7v07Tp5ZhM8lQw2Td+ZCEsAiFn2LwNxFoQPHVFvY6jW6bmBOWKOfoY2JodeUOuFT+yKezqXrNIdGgScvrCKoqb32iuTIQGINiTJHr9FJOyFLbzw6DlK/JIeSbkQquo4jszvMSGLZs6regcSNY+zqy7g/RfggYlpWQni3UFzmm/KeP5ggD47uUN9ALJzCyeD/CEbruMZIjlzs3DJM0lYk/SmWaz/wWoeadgF94RRxsOFSMTl7tIVcUcBaylSw5B3ARxtPrmd5uLmH30euPAq6DuALN3pOSN5V+9cYjYDm1s0melKW7m9K8FGd3HKgGGqBSPVuvROabCDLcOL/OgMmhamqk+X63zsKXiwPi6SxprcRsb+Yt4pJTNIcmaFdisotewPIBaW4Gco6qKC/iVskz+42RKvM1Uo7YgMRI6fWkUkzaD5Pj4T4xaEEes9AqLqBm2NexKGyGmKtRLhlTins7dkdlTp15A==
  template:
    metadata:
      creationTimestamp: null
      name: auth-generic-oauth-secret
      namespace: monitoring
