---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auth-generic-oauth-secret
  namespace: monitoring
spec:
  encryptedData:
    client_id: AgBmT0cqbGkXDpmVpaU2yDulw6pTO31uD/kocC5l8vqmnwdp4CKsmUEwkDj9YFUpG3d7uUHL6n1QfDMskOYJLZltzUgdIgK7gFBvcbjyitrUnyoIouRp/EI+nTQdGoU7bCLL3klIyyb18zAVB0B57ZLeHj/vfIFVevKZiKCotwzKGVW8Pci9ir2Y44zOI7l9KcLu0GSp4WueXZwziR+VmA/mTo6zFzEwxQitOSwKnE/3t1KraYoeAaREycfZOmLvjShv5Z07pY8agMwy4dwpgYkgs7mHpKoHvJ7LL2O9iC3zlAlZdU7nJqDKnIHdCDqbKuY0itnz0HviQ8EnXjks/jF4iR/aqixNEORR5n5VVvsMN2Mk37on+HQUYlpvatFB27JEkMcI5J6L8tMwMhvfnq5lU1SGk3zhitMAmuXzd++cTAK0S5FIWFghwNWFMIswkALvTZ0mc4pLbK9ytfJ74e3BDjfXwzvvd+bTSODAfLzYrzVS826/03Gcn+m4Gi6FczU5MTskO4hWZ7yrQUglBIjP2/N57g5bqzBLaY1NkQq/b4yLA/VZu5PoAHA0+qKUZlhPOlfebRP7rl7EAMCJ1l6DaVPeUb/0yW97plRalhv8dZSFMaVXZiEzKjkUKeaRhfi/B4oV1Hha05yhwVXYbmEX1wTk0RRNoPBnm66RGXw1p5zriIPAKM91ODUDjZACjPJuf7eMSPfjY9RAoZEu
    client_secret: AgAxo+cLjlfypKfTdMd0JZoD/sRlHBQwXVwzACgJxYt+NxI2H3ghA9++fhvPTPcvQ2szcuOIRrEIDhvTgQktQ/riMaEigInpOXNP67at2nVJ+o3cmqFJxnytqVPrjLpptFIvG5qzEj+ARBQaImg8AoTlJ+J/HKQs1aWARTOqBLkCXi6YFcuSphT/bvX2KOQC2n+P2DEskaa6pqPAX84bEitG8cDclX3Dw/e2K0TM6KU2UmG7apHXe96+OQedj3tXM076/uHQ4XvtKmk+n7I8dCaE2hZkxqAEWofvmx6647ZayEmw+QtNy2czzIc0zc/R2p9IEfkqoBdCvVvWBba26CNGKdfjd+n46CLvuj7QdK/ykjfnwWYyjQJnaDbI766uCC0plKNj7h5y06xkOM0GVE/h/ryPyStwjGAqNJnE9pTup4d4utgNAzKXzUDJXzUv1hP5+b8FYeRAS+DHrb7+AeKHTjsiH/opAlD/8CzJTfn3Dpe8g6QyrS/iIjnZQxgr4uQZ/2Whti3HamnuDUIx1VoCimb9Aplw4FLCT6RknltGBkAoUJc4vD/qJhmNwEPBSmRAM6wWzAg1VOTZekZRd++jrr5OCsb0fCVyfT3tcbHLsSJIdymjFkDFTzn63s6tqKkfquiV6mcx6tzeF3vCFZcmpESCaRLGdgbZCwBDipXnEavMzcl5syYONXwuN5IySgpe02SEknFO5Yfa3VrtUreEQ8oF6xvmUV8=
  template:
    metadata:
      creationTimestamp: null
      name: auth-generic-oauth-secret
      namespace: monitoring
