apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 60m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
      interval: 12h
  values:
    alertmanager:
      alertmanagerSpec:
        replicas: 3
    prometheus:
      prometheusSpec:
        replicas: 3

    grafana:
      enabled: true
      replicas: 1
      extraSecretMounts:
        - name: auth-generic-oauth-secret-mount
          secretName: auth-generic-oauth-secret
          defaultMode: 0440
          mountPath: /etc/secrets/auth_generic_oauth
          readOnly: true


      additionalDataSources:
        - name: loki
          type: loki
          url: http://loki-read.monitoring.svc.cluster.local:3100
          jsonData:
            tlsSkipVerify: true
            httpHeaderName1: "X-Scope-OrgID"
          secureJsonData:
            httpHeaderValue1: "admins"


      grafana.ini:
        server:
          domain = grafana.monitoring.apoorva64.com
          root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
          serve_from_sub_path = true
        auth.generic_oauth:
          enabled: true
          auto_login: false
          name: "Keycloak-OAuth"
          allow_sign_up: true
          client_id: $__file{/etc/secrets/auth_generic_oauth/client_id}
          client_secret: $__file{/etc/secrets/auth_generic_oauth/client_secret}
          scopes: "openid profile email roles offline_access"
          email_attribute_path: "email"
          login_attribute_path: "preferred_username"
          name_attribute_path: "name"
          auth_url: "https://keycloak.auth.apoorva64.com/realms/lab/protocol/openid-connect/auth"
          token_url: "https://keycloak.auth.apoorva64.com/realms/lab/protocol/openid-connect/token"
          api_url: "https://keycloak.auth.apoorva64.com/realms/lab/protocol/openid-connect/userinfo"
          allow_assign_grafana_admin: true
          role_attribute_path: "contains(resource_access.grafana_oauth.roles[*], 'admin') && 'GrafanaAdmin' || contains(resource_access.grafana_oauth.roles[*], 'editor') && 'Editor' || 'Viewer'"
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - grafana.monitoring.apoorva64.com
        tls:
          - secretName: grafana-tls
            hosts:
              - grafana.monitoring.apoorva64.com
        path: /grafana
      # Provision grafana-dashboards-kubernetes
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
            - name: 'grafana-dashboards-kubernetes'
              orgId: 1
              folder: 'Kubernetes'
              type: file
              disableDeletion: true
              editable: true
              options:
                path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes
            - name: 'loki-dashboard'
              orgId: 1
              folder: 'Loki'
              type: file
              disableDeletion: true
              editable: true
              options:
                path: /var/lib/grafana/dashboards/loki

      dashboards:
        grafana-dashboards-kubernetes:
          k8s-system-api-server:
            url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
            token: ''
          k8s-system-coredns:
            url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-coredns.json
            token: ''
          k8s-views-global:
            url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
            token: ''
          k8s-views-namespaces:
            url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json
            token: ''
          k8s-views-nodes:
            url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
            token: ''
          k8s-views-pods:
            url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
            token: ''
        loki:
          loki:
            token: ''
            json: |
              {
                "annotations": {
                  "list": [
                    {
                      "builtIn": 1,
                      "datasource": {
                        "type": "datasource",
                        "uid": "grafana"
                      },
                      "enable": true,
                      "hide": true,
                      "iconColor": "rgba(0, 211, 255, 1)",
                      "name": "Annotations & Alerts",
                      "target": {
                        "limit": 100,
                        "matchAny": false,
                        "tags": [],
                        "type": "dashboard"
                      },
                      "type": "dashboard"
                    }
                  ]
                },
                "description": "Logs collected from Kubernetes, stored in Loki",
                "editable": true,
                "fiscalYearStartMonth": 0,
                "gnetId": 15141,
                "graphTooltip": 0,
                "links": [],
                "liveNow": false,
                "panels": [
                  {
                    "datasource": {
                      "type": "loki",
                      "uid": "P982945308D3682D1"
                    },
                    "description": "",
                    "fieldConfig": {
                      "defaults": {
                        "color": {
                          "mode": "palette-classic"
                        },
                        "custom": {
                          "axisCenteredZero": false,
                          "axisColorMode": "text",
                          "axisLabel": "",
                          "axisPlacement": "auto",
                          "barAlignment": 0,
                          "drawStyle": "bars",
                          "fillOpacity": 0,
                          "gradientMode": "none",
                          "hideFrom": {
                            "legend": false,
                            "tooltip": false,
                            "viz": false
                          },
                          "lineInterpolation": "linear",
                          "lineWidth": 1,
                          "pointSize": 5,
                          "scaleDistribution": {
                            "type": "linear"
                          },
                          "showPoints": "auto",
                          "spanNulls": false,
                          "stacking": {
                            "group": "A",
                            "mode": "none"
                          },
                          "thresholdsStyle": {
                            "mode": "off"
                          }
                        },
                        "mappings": [],
                        "thresholds": {
                          "mode": "absolute",
                          "steps": [
                            {
                              "color": "green",
                              "value": null
                            },
                            {
                              "color": "red",
                              "value": 80
                            }
                          ]
                        }
                      },
                      "overrides": []
                    },
                    "gridPos": {
                      "h": 4,
                      "w": 24,
                      "x": 0,
                      "y": 0
                    },
                    "id": 4,
                    "options": {
                      "legend": {
                        "calcs": [],
                        "displayMode": "list",
                        "placement": "bottom",
                        "showLegend": false
                      },
                      "tooltip": {
                        "mode": "single",
                        "sort": "none"
                      }
                    },
                    "targets": [
                      {
                        "datasource": {
                          "type": "loki",
                          "uid": "P982945308D3682D1"
                        },
                        "expr": "sum(count_over_time({namespace=~\"$namespace\", stream=~\"$stream\", container =~\"$container\"} |= \"$query\" [$__interval]))",
                        "instant": false,
                        "legendFormat": "Log count",
                        "range": true,
                        "refId": "A"
                      }
                    ],
                    "type": "timeseries"
                  },
                  {
                    "datasource": {
                      "type": "loki",
                      "uid": "P982945308D3682D1"
                    },
                    "description": "Logs from services running in Kubernetes",
                    "gridPos": {
                      "h": 25,
                      "w": 24,
                      "x": 0,
                      "y": 4
                    },
                    "id": 2,
                    "options": {
                      "dedupStrategy": "none",
                      "enableLogDetails": true,
                      "prettifyLogMessage": true,
                      "showCommonLabels": false,
                      "showLabels": false,
                      "showTime": false,
                      "sortOrder": "Descending",
                      "wrapLogMessage": true
                    },
                    "targets": [
                      {
                        "datasource": {
                          "type": "loki",
                          "uid": "P982945308D3682D1"
                        },
                        "expr": "{namespace=~\"$namespace\", stream=~\"$stream\", container =~\"$container\"} |= \"$query\"",
                        "refId": "A"
                      }
                    ],
                    "type": "logs"
                  }
                ],
                "refresh": "",
                "schemaVersion": 38,
                "style": "dark",
                "tags": [],
                "templating": {
                  "list": [
                    {
                      "current": {
                        "selected": false,
                        "text": "",
                        "value": ""
                      },
                      "description": "String to search for",
                      "hide": 0,
                      "label": "Search Query",
                      "name": "query",
                      "options": [
                        {
                          "selected": true,
                          "text": "",
                          "value": ""
                        }
                      ],
                      "query": "",
                      "skipUrlSync": false,
                      "type": "textbox"
                    },
                    {
                      "allValue": ".+",
                      "current": {
                        "selected": true,
                        "text": [
                          "flux-system"
                        ],
                        "value": [
                          "flux-system"
                        ]
                      },
                      "datasource": {
                        "type": "loki",
                        "uid": "P982945308D3682D1"
                      },
                      "definition": "label_values(namespace)",
                      "hide": 0,
                      "includeAll": true,
                      "multi": true,
                      "name": "namespace",
                      "options": [],
                      "query": "label_values(namespace)",
                      "refresh": 1,
                      "regex": "",
                      "skipUrlSync": false,
                      "sort": 0,
                      "type": "query"
                    },
                    {
                      "allValue": ".+",
                      "current": {
                        "selected": false,
                        "text": "All",
                        "value": "$__all"
                      },
                      "datasource": {
                        "type": "loki",
                        "uid": "P982945308D3682D1"
                      },
                      "definition": "label_values(stream)",
                      "hide": 0,
                      "includeAll": true,
                      "multi": true,
                      "name": "stream",
                      "options": [],
                      "query": "label_values(stream)",
                      "refresh": 1,
                      "regex": "",
                      "skipUrlSync": false,
                      "sort": 0,
                      "type": "query"
                    },
                    {
                      "allValue": ".+",
                      "current": {
                        "selected": false,
                        "text": "All",
                        "value": "$__all"
                      },
                      "datasource": {
                        "type": "loki",
                        "uid": "P982945308D3682D1"
                      },
                      "definition": "label_values(container)",
                      "hide": 0,
                      "includeAll": true,
                      "multi": true,
                      "name": "container",
                      "options": [],
                      "query": "label_values(container)",
                      "refresh": 1,
                      "regex": "",
                      "skipUrlSync": false,
                      "sort": 0,
                      "type": "query"
                    }
                  ]
                },
                "time": {
                  "from": "now-6h",
                  "to": "now"
                },
                "timepicker": {},
                "timezone": "",
                "title": "Loki Kubernetes Logs",
                "uid": "o6-BGgnnk",
                "version": 1,
                "weekStart": ""
              }
