apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 60m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
      interval: 12h
  values:
    alertmanager:
      ingress:
        enabled: false
        annotations:
          kubernetes.io/ingress.class: traefik
          cert-manager.io/cluster-issuer: letsencrypt-prod
          traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
        hosts:
          - alertmanager.monitoring.apoorva64.com
        tls:
          - secretName: alertmanager-tls
            hosts:
              - alertmanager.monitoring.apoorva64.com
        paths:
          - /
    grafana:
      extraSecretMounts:
        - name: auth-generic-oauth-secret-mount
          secretName: auth-generic-oauth-secret
          defaultMode: 0440
          mountPath: /etc/secrets/auth_generic_oauth
          readOnly: true
      grafana.ini:
        server:
          root_url: https://grafana.monitoring.apoorva64.com
        auth.generic_oauth:
          enabled: true
          name: "Keycloak-OAuth"
          allow_sign_up: false
          client_id: $__file{/etc/secrets/auth_generic_oauth/client_id}
          client_secret: $__file{/etc/secrets/auth_generic_oauth/client_secret}
          scopes: "openid email profile offline_access roles"
          email_attribute_path: "email"
          login_attribute_path: "preferred_username"
          name_attribute_path: "name"
          auth_url: "https://keycloak.auth.apoorva64.com/auth/realms/lab/protocol/openid-connect/auth"
          token_url: "https://keycloak.auth.apoorva64.com/auth/realms/lab/protocol/openid-connect/token"
          api_url: "https://keycloak.auth.apoorva64.com/auth/realms/lab/protocol/openid-connect/userinfo"
          role_attribute_path: "contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'editor') && 'Editor' || 'Viewer'"
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
          cert-manager.io/cluster-issuer: letsencrypt-prod
          traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
        hosts:
          - grafana.monitoring.apoorva64.com
        tls:
          - secretName: grafana-tls
            hosts:
              - grafana.monitoring.apoorva64.com
        paths:
          - /
    prometheus:
      ingress:
        enabled: false
        annotations:
          kubernetes.io/ingress.class: traefik
          cert-manager.io/cluster-issuer: letsencrypt-prod
          traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
        hosts:
          - prometheus.monitoring.apoorva64.com
        tls:
          - secretName: prometheus-tls
            hosts:
              - prometheus.monitoring.apoorva64.com
        paths:
          - /