apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../../base/spos
  - mongo-db
  - backend

namespace: spos-prod
patchesStrategicMerge:
  # patch kustomize to reference to prod manifests
  - kustomize-patch.yaml

# Place all deployments on amd64 nodes

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: backend
      spec:
        template:
          spec:
            nodeSelector:
              beta.kubernetes.io/arch: amd64