apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../../base/spos
  - mongo-db

namespace: spos-prod
patchesStrategicMerge:
  # patch kustomize to reference to prod manifests
  - kustomize-patch.yaml