apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: prod-mongo-db
spec:
  members: 1
  type: ReplicaSet
  version: "4.4.15"
  security:
    authentication:
      modes: [ "SCRAM" ]
  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: admin-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: scram-credentials
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib