apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../../base/spos

namespace: spos-dev
patchesStrategicMerge:
  # patch kustomize to reference to develop manifests
  - kustomize-patch.yaml