apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: si4-ml-digits-recognition
  namespace: flux-system
spec:
  interval: 5m
  path: ./manifests/react-flight-tracker/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: si4-ml-digits-recognition