apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb-secrets
  namespace: keycloak
spec:
  encryptedData:
    mariadb-secrets.yaml: AgBU8zz7YSE43/fZMWFzjQ+MpyzpcGAav+eYyrXgG6XizZIX8RXLqQn27CjzUEVwryaTiB8qeZWO1HdN5uTUvcr9HEP/I9hUf3x8La1OZu4cAIbY3Jj8k7bp9cwtCXjXfoZp7QyuSo1JXeji1CYDdiwdvw9SvVlgIVzyywxZjEf44cipMl54nFpC7y9fxDDiP3UtqgYF7SS+ryAtUYF8UfPqJ1XJfKdspDc5Htnh756pN3VMaiIK6L5jBISftfkQYQkBaI2WFNtyTH4E5qDJxnsdkjLLj0dDwCHFuZX57ax7lE2G6Y+e8DMvfbnTGpgsu5XrGAnKchRaOjD6O9AzyT0vN73/aXs/LnHXK0/m0/ZD90gPK8IsDf9D/K1/+by1aPg7ol5E6SEBEGaqQf9uezmDOEBgK8UmTJhDuy4cgP623AcnCwRqlw56swkOCBUM7Qt3OIlqdGUIZvAmMzLvzSjoYbuMzDL5FbNaqQqCeHHq1d0ds5hP4UUD16h14kccNYKegTThE7xrhEJlNgV6eLySNEIr3RgK0ug5rzjnkmEFyZApCKOpr2xptk4RHCtv5S8dXRzp7a70UrVcp43madMIdv/YyqMlsyqiqb7AN9eALvwCyuAzLkY2JNeBDBA+NxgOvg1OSfpHAeYMX51IATwLb13KK0W/39OJWmvOLX4SPiJ10ielknsI231K3Q6747YVRVUm9jzwD3AwagepG2kVcW84pf9emzyI5pyICf1XJYkGyAVhIZ6xway84IdVAArK2bK3aHZ5tZadarakweJ7c9EUCP6uhR97LW81cQ1U0+z96FEKEG9ZPsaV3cI3L8h1YaPnLW5erqFNMeXBGsEcscn1+Kp3kyOB0ZXuX6W9InQ6s5EboFVMLCIcvGjrTgPyAsfH2hbttOJ8szcf0nBKCTQggJcl6hKgLUol2jI1+NIyizUXS9ccVdHDi7fdmjWiPBkGrdWzf6zsoGlF900=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mariadb-secrets
      namespace: keycloak

