apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb-secrets
  namespace: keycloak
spec:
  encryptedData:
    mariadb-secrets.yaml: AgDcPg86Xn/TnIxM/lJiYDzZ1HUUpgnE5JElzQfeSLPIQvY/4ejd1cHLZaIapmlrOw24y+9pzTR5eH3cOMOL0djxK0Q0spiNC2Bx0ACCdvR7adm6hGIi01P2b7cP5tcgMb7d4JTGYfM83d0qm4vbdjxDyJid2k/SvMojzGHCEcLN1px9S+AHqV/vW4m4s2BdpwLMhFNT8Twax5H7zGmwvq7mepRVAHm9xq4iqN4Q487JtOxcUZV3ff3DPdAITfyVB50CsEtdryNscNWA5Bky8A8cv11YAeFmgxxAYB6puXgEFYOcp4tM1nSDfyidH5R3VxYK9nLE3B3K3eNgTZb9kwTimxCdFb6XEocR/e/+CF63bNxTx0MgIEWH5tIYrXcs8lU4he+bPmU4Af+gENRcOEssToBiJhFO++OmDtoeuN3u5Jlj6U2ubh6YCN1MuZQ61MoxvxA2dImp3E/dxtsP6ryrdo8kTYXyVnrH5z9FygexHI5uOACqarwgwhcB6h62qs5NnvJhyYAaX0mT15Mki92xWUOpdv6tP/46VHEDkufeb5oqockqoAaiejcuxcwPz0N9FPgWgZU2Ww1zb8rToBklSMHbJ1vkVh7+wG0VY1MlbBoGfNMUDmXrtQpf3g5MXFaIgFrLD5Akqh4lxy8lSeWa2rntMVKYrDo/7rf7GNzOJyCZCoYPwmgALtF+jg8mF6cXAXaUtXo2dfQkNASbgp9jW6YwMGy7xAGTgA06gXupQ7cLawniDF5hp6K+4/lHcTNY0wcOYLiEKEDZevk+lHCAPKwAVBKdl1zGtEd4qxUaP7nARzFml0pimte9bLDFFWjYALX3ab5Q1aygcH/Hvt9/fPWXQQu0K4B37iGLUS+06dI1Hz5hlUysW4hTcbBI/0A4vBGwoZyEvH7SKtuQWk9uedA7yw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mariadb-secrets
      namespace: keycloak

