apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 60m
  chart:
    spec:
      chart: oauth2-proxy
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: oauth2-proxy
      interval: 12h

  values:
    ingress:
      enabled: true
      className: traefik
      pathType: Prefix
      hosts:
        - oauth2-proxy.auth.apoorva64.com
      tls:
        - secretName: oauth2-proxy-tls
          hosts:
            - oauth2-proxy.auth.apoorva64.com
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd

  valuesFrom:
    - kind: Secret
      name: oauth2-proxy-config
      valuesKey: config.yaml
      optional: false