apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - oauth2-proxy-secret-sealed.yaml
  - helm-repository.yaml
  - helm-release.yaml
  - oauth2-forward-auth-middleware.yaml
  - oauth2-sign-in-redirect-middleware.yaml