apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth2-forward-auth
  namespace: default
spec:
  forwardAuth:
    address: https://oauth2-proxy.auth.apoorva64.com/oauth2/auth
    trustForwardHeader: true
    authResponseHeaders:
      - X-Forwarded-User