apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth2-forward-auth
  namespace: default
spec:
  errors:
    status:
      - "401-403"
    service:
      name: oauth2-proxy
      port: 80
      namespace: oauth2-proxy
    query: "/oauth2/sign_in"
