apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: sign-in-redirect-auth
  namespace: oauth2-proxy
spec:
  errors:
    status:
      - "401-403"
    service:
      name: oauth2-proxy
      namespace: oauth2-proxy
      port: 80
    query: "/oauth2/sign_in"
