apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: storage
spec:
  interval: 60m
  chart:
    spec:
      chart: minio
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 12h
  values:
    mode: distributed
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
      hostname: 'minio.storage.apoorva64.com'
      path: /
      tls:
        - hosts:
            - minio.storage.apoorva64.com
          secretName: minio-tls
    apiIngress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
      hostname: 'api.minio.storage.apoorva64.com'
      path: /
      tls:
        - hosts:
            - api.minio.storage.apoorva64.com
          secretName: api-minio-tls
    extraEnvVars:
      - name: MINIO_PROMETHEUS_URL
        value: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
      - name: MINIO_PROMETHEUS_JOB_ID
        value: "minio"
      - name: MINIO_PROMETHEUS_AUTH_TYPE
        value: "public"