apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-env
  namespace: storage
spec:
  encryptedData:
    MINIO_IDENTITY_OPENID_CLIENT_SECRET_KEYCLOAK_PRIMARY: AgAYygYuNjtAFxfjIe0j0TZpn7ujrRQKwTndSKSySeBQo9fsWYYk1X3sENqmiHjgisau4pMffAxapK2kuZ5fvnGqSUjhc95aoUI2yPZdMKgYV94xLlqAdbAMzxIWxyfezZuUvKIzeo/F++v9tg53aco7EvSV651KbcFphOWaT7l8MvjF0B7wSxCZlXwv1u+3Lfw3OUh0C5bChaFsIOAdZb7fTuD/z2BQ0MEcYtiNWhRrjwib+6SWKC5MUvdomE8S6Rp0M1l1z0YFVW4vZ/GfS4pfSzArdwGzaHAQJp7QT0SE86Y8zbbzPuifOn3WCaD+2fFaLhvBrIBs2MOnx2ptIop6MrDuroSPcrpiesPF6VK1UVcghVRDTYmrP2cdO8SN9/BAqU0WYSKLD5QfLbfNnrQZjdvmFj40WqALIYodiCrXxgiLoP20UgAsnU8z+v4bpxZmX4435zN072G780DgaJFttKJIfjmFq2iRdGaqQ04es0WIJmn4Vv56pFkzM2kFXW5KKvwEPENJIZjs2FzhZo4c43D124HBuNUcBgCwyA34eq/nUUVUlrcNq299toOidQcRf5wQK26glloQ2dzPOswO1WR1EpMfTIymECXrLloMQ83OMfhkD7/Y43/rW3AQ3lapNCN+bmnM3GUSNTXegzsq4bDdT5WrSivXvWZk2s+D1MTX1HGNoHgLJ2SezRbCOQpmOsQRzdn9/o8q2HcO204yuwO9ZUsTiiaxNw8hpPe0ow==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: minio-env
      namespace: storage

