apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: minio
  namespaceSelector:
    matchNames:
      - storage
  endpoints:
    - targetPort: 9000
      interval: 15s
      path: /minio/v2/metrics/cluster
      scheme: http
      followRedirects: false
      scrapeTimeout: 30s
  jobLabel: minio
