apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: minio
  endpoints:
    - targetPort: 9000
      interval: 15s
      path: /minio/v2/metrics/cluster
      scheme: http
      tlsConfig:
        insecureSkipVerify: true
  jobLabel: minio