apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 60m
  chart:
    spec:
      chart: traefik
      version: "25.0.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 12h
  values:
    deployment:
      replicas: 8
    ingressRoute:
      dashboard:
        enabled: true
    podAnnotations:
      prometheus.io/port: "8082"
      prometheus.io/scrape: "true"
      providers:
        kubernetesIngress:
          publishedService:
            enabled: true
      priorityClassName: "system-cluster-critical"
      image:
        repository: "rancher/mirrored-library-traefik"
        tag: "2.10.5"
      #      tolerations:
      #        - key: "CriticalAddonsOnly"
      #          operator: "Exists"
      #        - key: "node-role.kubernetes.io/control-plane"
      #          operator: "Exists"
      #          effect: "NoSchedule"
      #        - key: "node-role.kubernetes.io/master"
      #          operator: "Exists"
      #          effect: "NoSchedule"
      service:
        ipFamilyPolicy: "PreferDualStack"
    metrics:
      ## -- Prometheus is enabled by default.
      ## -- It can be disabled by setting "prometheus: null"
      prometheus:
        # -- Entry point used to expose metrics.
        entryPoint: metrics
        addEntryPointsLabels: true
        addServicesLabels: true
        addRoutersLabels: true
    experimental:
      plugins:
        enabled: true
        sablier:
          moduleName: "github.com/acouvreur/sablier"
          version: "v1.6.0"
        keycloakopenid:
          moduleName: "github.com/Gwojda/keycloakopenid"
          version: "v0.1.35"
    env:
      - name: "KEYCLOAK_URL"
        value: "keycloak.auth.apoorva64.com"
      - name: "KEYCLOAK_REALM"
        value: "lab"
      - name: "KEYCLOAK_CLIENT_ID"
        valueFrom:
          secretKeyRef:
            name: keycloak-auth
            key: client-id
      - name: "KEYCLOAK_CLIENT_SECRET"
        valueFrom:
          secretKeyRef:
            name: keycloak-auth
            key: client-secret