apiVersion: v1
kind: Service
metadata:
  name: traefik-metrics
  namespace: kube-system
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/component: metrics
    helm.sh/chart: traefik-26.0.0
    heritage: Helm
    release: traefik
spec:
  selector:
    app.kubernetes.io/name: traefik
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 9100
      name: metrics
