apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: nuit-info-2023
  namespace: flux-system
spec:
  interval: 5m
  path:  ./manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: nuit-info-2023