---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-permissions
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: devops-tools
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./permissions/apps
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-apps
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: devops-tools
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/dev
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-apps
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: devops-tools
    - name: apps-permissions
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/prod
  prune: true
  wait: true
  timeout: 5m0s