apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: satellite-api-react-flight-tracker
spec:
  interval: 5m
  path: ./manifests/overlays/develop
  prune: true
  serviceAccountName: flux-cd-base
  sourceRef:
    kind: GitRepository
    name: satellite-api-react-flight-tracker
  patches:
    - patch: |-
        # set ressources of the first container to 100m CPU and 100Mi memory
        - op: replace
          path: /spec/template/spec/containers/0/resources
          value:
            limits:
              cpu: 2000m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 100Mi
      target:
        kind: Deployment
