apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: satellite-api-react-flight-tracker
spec:
  interval: 5m
  path: ./manifests/overlays/develop
  prune: true
  serviceAccountName: flux-cd-base
  sourceRef:
    kind: GitRepository
    name: satellite-api-react-flight-tracker