---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: spacetrack-crendentials
spec:
  encryptedData:
    password: AgB/zG+oN1HE5H16W9eatfBJfL9brkl2SUfKleBwMxIq9Sz3UgSj9cZAAuQ/pViHlGceRM64k4oxULS7XTrh70c1eKwJvCwnReBvdgA0WLdkZiuE7mtioWpg3IjYlQf+ncD42/x6NwrSBUIoi8JkZUYI+9O0g9jnRS+0hUbwglyIArkFpKuR2jkXkZ//edOb5xc71G+K5hvnzR1m83nXQISSO+HI+N7iU49eIUW4wM3l071ly0H4PuvD+WOOEQYVpKOfXYK50wLw2jtUFaXztGEaw5oz8YlYUT7a4PBNewNVW61r6ZJqMMdVLvmdmpLQL09hhaaAuiAVYyw8qWM4wv+xcBEcXPgYHgcrKsNmGMUQTMGPe5zYZp3fwEL9SIjedcPPLVFzNflxPC8B/wtl/RLhQtULZshfgmx9cRhq8WT+IM5Ykxha6v6Y24B6NSPXwwDYKz7KgEZkheIqzftt4l1yB8v9d5bQGt48Dav9ILzpOF1HccP5FRsqcHIAumFL5fxre2lmYxAJqQ5sJzrd4rU/RNMOFUy7KW4BU2fczH2VcoJZGmPJsdsGrWRsKhI5U2/hWkuVc6/dVDHVAL9rQnSFsPEQdbJPhFxuBAHZaP60Z/eNmJWhJ1zLdIgTTN1vxJxHYrEprnHCE+pTeJrHtUjI6z7q8FKuLo/dzH+g7tj8rw/yakU5k69bOHobDEReptVyVzA7mUFYfbIGfgrixUI=
    username: AgBBchCh/3R+GZFQr/0AtIT1sFN2Eq/WdhNNMkf29XT/smehJ157h5bG9JCdifWhteUkENtZQ1SoGgg0UY334b/HuL24jru5iB6D+E915h2pY2rbvxKbQ+t33V9nJF1jcxI0COfP0fMxejga2jqA8+VMheoG/xQFi40rTJ4u6tfSLA17yuXWoGeb7T67xs/mAYGSrIVI4mmUeIdMYmjw0CkzozUvSRoTB468fqM4oFWcQ2V7ul8PSeFLLLtA9fQoRxva8VF1BnrGxn461bjsaBVk+DQF3OgLdieX1IIGujNMn3fuOny7yzM+WUjIUoi/D6v4YVakHWGSc0xEFXPB67FO/IsUhUEjI6251XyQfUqJ1steb14lnTTU5K+c2XjIzMvQCDPIGuiN90b4VLeJBVxkPaSgvYkFjecHW70dWC6DYlXk4EjnFooGK1BInDdab0US8aksICgWSVX7Ofoi+uesPIQsT+E6hUoM85S/53Vzg0CSaFDpaYJIcIoZKDrbIQGJXG2ObOMb/qZxn9A9LvmLS3/uNoH/hWK8eeJAPh2jTA4t6gFa97HTVHemsS4UdOrpF8dcA9GwI3VbtzUVOTV7adHGQKxVHiroRug4pEWJJynL+Xnss3Z0aJpMX99HgBeTRI4BQBT+Ny723u3MopP4fnyn7upTBPB8k3zFAiYifc8OHLY9+yNnqQT0WX3JVecbNhRRyYIkOBWGNJ8qXbzo2YPK789/Ch0=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: spacetrack-crendentials
    type: Opaque
