apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repository.yaml
  - kustomize.yaml
  - rbac

patches:
  - target:
      kind: Deployment
    patch: |
      - op: add
        path: /spec/template/spec/dnsConfig
        value:
          options:
            - name: ndots
              value: "1"