apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: spos
spec:
  interval: 5m
  path: ./manifest/develop
  prune: true
  serviceAccountName: flux-cd-base
  sourceRef:
    kind: GitRepository
    name: spos
  patches:
    # prefer amd64 nodes
    - target:
        kind: Deployment
      patch: |-
        - op: add
          path: /spec/template/spec/nodeSelector
          value:
            kubernetes.io/hostname: node-apoorva3