apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: redbot-claim0
  name: redbot-claim0
  namespace: red-discord-bot
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-single-replica
  resources:
    requests:
      storage: 1Gi
status: { }
