apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: redbot-claim0
  name: redbot-claim0
  namespace: red-discord-bot
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
      storageClassName: local-path
status: {}
