apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: video-transcoder-2
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/Apoorva64/video-transcoder-2
  ref:
    branch: master