---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mc-router
  namespace: minecraft
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-stable
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: services-watcher
rules:
  - apiGroups: [ "" ]
    resources: [ "services" ]
    verbs: [ "watch","list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mc-router-services-watcher
subjects:
  - kind: ServiceAccount
    name: mc-router
    namespace: minecraft
roleRef:
  kind: ClusterRole
  name: services-watcher
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: mc-router
  namespace: minecraft
spec:
  type: NodePort
  ports:
    - targetPort: web
      name: web
      port: 8080
      nodePort: 30080
    - targetPort: proxy
      name: proxy
      port: 25565
      nodePort: 30000
  selector:
    run: mc-router
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: mc-router
  name: mc-router
  namespace: minecraft
spec:
  selector:
    matchLabels:
      run: mc-router
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: mc-router
    spec:
      serviceAccountName: mc-router
      containers:
        - image: itzg/mc-router:latest
          name: mc-router
          args: [ "--api-binding", ":8080", "--in-kube-cluster" ]
          ports:
            - name: proxy
              containerPort: 25565
            - name: web
              containerPort: 8080
          resources:
            requests:
              memory: 50Mi
              cpu: "100m"
            limits:
              memory: 100Mi
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: mc-stable
  namespace: minecraft
  annotations:
    "mc-router.itzg.me/externalServerName": "minecraft.games.apoorva64.com"
spec:
  ports:
    - port: 25565
  selector:
    run: mc-stable
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: mc-stable
  name: mc-stable
  namespace: minecraft
spec:
  selector:
    matchLabels:
      run: mc-stable
  template:
    metadata:
      labels:
        run: mc-stable
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - image: itzg/minecraft-server
          name: mc-stable
          env:
            - name: EULA
              value: "TRUE"
            - name: ONLINE_MODE
              value: "FALSE"
            - name: SERVER_NAME
              value: "Apoorva's Minecraft Server"
            - name: CF_API_KEY
              valueFrom:
                secretKeyRef:
                  name: curseforge-api-key
                  key: api-key
            - name: TYPE
              value: "AUTO_CURSEFORGE"
            - name: CF_PAGE_URL
              value: "https://www.curseforge.com/minecraft/mc-mods/easyauth"
          ports:
            - containerPort: 25565
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mc-stable
