apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-world
  namespace: minecraft
  labels:
    app: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
