apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
  namespace: minecraft
spec:
  selector:
    app.kubernetes.io/name: minecraft-server
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
      name: game-port
    - protocol: UDP
      port: 25565 # This is the port that the Minecraft client will connect to
      targetPort: 25565
      name: game-port-udp