apiVersion: apps/v1
kind: Deployment
metadata:
  name: speaches
  namespace: speaches
  labels:
    app: speaches
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speaches
  template:
    metadata:
      labels:
        app: speaches
    spec:
      containers:
        - name: speaches
          image: ghcr.io/speaches-ai/speaches:latest-cuda-12.4.1
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
      runtimeClassName: nvidia
---
apiVersion: v1
kind: Service
metadata:
  name: speaches
  namespace: speaches
spec:
  selector:
    app: speaches
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Namespace
metadata:
  name: speaches