apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: minio-operator
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/minio/operator/

  ref:
    branch: master