apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: devops-tools
spec:
  interval: 60m
  chart:
    spec:
      chart: gitlab-runner
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
      interval: 12h
  values:
    gitlabUrl: https://gitlab.com
    runners:
      # runner configuration, where the multi line strings is evaluated as
      # template so you can specify helm values inside of it.
      #
      # tpl: https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-tpl-function
      # runner configuration: https://docs.gitlab.com/runner/configuration/advanced-configuration.html
      config: |
        [[runners]]
          [runners.kubernetes]
            namespace = "{{.Release.Namespace}}"
            image = "ubuntu:16.04"
      privileged: true
