apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: devops-tools
spec:
  interval: 60m
  chart:
    spec:
      chart: gitlab-runner
      version: "0.50.0"
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
      interval: 12h
  values:
    rbac:
      create: true
    gitlabUrl: https://gitlab.com
    concurrent: 4
    runners:
      secret: gitlab-runner
      cache:
        secretName: gitlab-runner-s3-access
      config: |
        log_level = "debug"
        [[runners]]
          [runners.kubernetes]
            image = "ubuntu:20.04"
            helper_image = "gitlab/gitlab-runner-helper:arm64-1278d3da"
            privileged = true
          [[runners.kubernetes.volumes.empty_dir]]
            name = "docker-certs"
            mount_path = "/certs/client"
            medium = "Memory"
          [runners.cache]
            Type = "s3"
            Shared = true
            [runners.cache.s3]
              ServerAddress = "minio.storage.svc.cluster.local:9000"
              BucketName = "gitlab-runners-cache"
              BucketLocation = "eu-central-1"
              Insecure = true
              AuthenticationType = "access-key"