apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: devops-tools
spec:
  interval: 60m
  chart:
    spec:
      chart: gitlab-runner
      version: "0.53.2"
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
      interval: 12h
  values:
    rbac:
      create: true
    gitlabUrl: https://gitlab.com
    concurrent: 4
    runners:
      cache:
        - secretName: gitlab-runner-s3-access
      config: |
        log_level = "debug"
        [[runners]]
          [runners.kubernetes]
            image = "ubuntu:latest"
            helper_image = "gitlab/gitlab-runner-helper:arm64-1278d3da"
            privileged = true
          [runners.cache]
            Type = "s3"
            Shared = true
            [runners.cache.s3]
              ServerAddress = "api.minio.storage.apoorva64.com"
              BucketName = "gitlab-runners-cache"
              BucketLocation = "eu-centeral-1"
              Insecure = false
              AuthenticationType = "access-key"