apiVersion: pingcap.com/v1alpha1
kind: TidbInitializer
metadata:
  name: keycloak-db-init
  namespace: keycloak
spec:
  image: bedinotom/mysql:ap-arm64-v2
  cluster:
    namespace: keycloak
    name: keycloak-db
  initSql: |-
    create database keycloak;
  passwordSecret: tidb-secret