# IT IS NOT SUITABLE FOR PRODUCTION USE.
# This YAML describes a keycloak-db TiDB cluster with minimum resource requirements,
# which should be able to run in any Kubernetes cluster with storage support.
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: keycloak-db
  namespace: keycloak
spec:
  version: v7.1.1
  timezone: UTC
  pvReclaimPolicy: Retain
  enableDynamicConfiguration: true
  configUpdateStrategy: RollingUpdate
  discovery: {}
  helper:
    image: alpine:3.16.0
  pd:
    requests:
      storage: "4Gi"
    replicas: 3
    # if storageClassName is not set, the default Storage Class of the Kubernetes cluster will be used
    storageClassName: local-path
  tikv:
    requests:
      storage: "4Gi"
    storageClassName:  local-path
    replicas: 3
  tidb:
    replicas: 3
    storageClassName: local-path

---
apiVersion: pingcap.com/v1alpha1
kind: TidbDashboard
metadata:
  name: keycloak-db
  namespace: keycloak
spec:
  baseImage: pingcap/tidb-dashboard
  version: latest

  ## tidb cluster to be monitored
  ## ** now only support monitoring one tidb cluster **
  clusters:
    - name: keycloak-db

  ## describes the compute resource requirements and limits.
  ## Ref: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
  requests:
    #   cpu: 1000m
    #   memory: 1Gi
    storage: 10Gi
  storageClassName: local-path
  # limits:
  #   cpu: 2000m
  #   memory: 2Gi


#---
#apiVersion: pingcap.com/v1alpha1
#kind: TidbInitializer
#metadata:
#  name: keycloak-db-init
#  namespace: keycloak
#spec:
#  image: bedinotom/mysql:ap-arm64-v2
#  cluster:
#    namespace: keycloak
#    name: keycloak-db
#  initSql: |-
#    create database keycloak;
#  passwordSecret: tidb-secret