apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bdns
  namespace: bdns
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 60m
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
            patch: |
              - op: add
                path: /spec/template/spec/dnsConfig
                value:
                  options:
                    - name: ndots
                      value: "1"
  chart:
    spec:
      chart: ./charts/bdns
      interval: 5m0s
      sourceRef:
        kind: GitRepository
        name: bdns
        namespace: bdns
  values:
    bdns_api:
      ingress:
        enabled: true
        hosts:
          - host: bdns.polytech.apoorva64.com
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: bdns-tls
            hosts:
              - bdns.polytech.apoorva64.com
    blacklist_api:
      ingress:
        enabled: true
        hosts:
          - host: blacklist.polytech.apoorva64.com
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: blacklist-tls
            hosts:
              - blacklist.polytech.apoorva64.com
    eck-operator:
      enabled: false
    kube-prometheus-stack:
      enabled: true
      alertmanager:
        enabled: false
      nodeExporter:
        enabled: false
      ## Flag to disable all the kubernetes component scrapers
      ##
      kubernetesServiceMonitors:
        enabled: false

      ## Component scraping the kube api server
      ##
      kubeApiServer:
        enabled: false
      kubelet:
        enabled: false
      kubeControllerManager:
        enabled: false
      coreDns:
        enabled: false
      kubeEtcd:
        enabled: false
      kubeScheduler:
        enabled: false
      kubeProxy:
        enabled: false
      kubeStateMetrics:
        enabled: false
      prometheusOperator:
        enabled: false
      prometheus:
        enabled: false