apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bdns
  namespace: bdns
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 60m
  chart:
    spec:
      chart: ./charts/bdns
      interval: 5m0s
      sourceRef:
        kind: GitRepository
        name: bdns
        namespace: bdns
  values:
    bdns_api:
      ingress:
        enabled: true
        hosts:
          - host: bdns.polytech.apoorva64.com
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: bdns-tls
            hosts:
              - bdns.polytech.apoorva64.com
    blacklist_api:
      ingress:
        enabled: true
        hosts:
          - host: blacklist.polytech.apoorva64.com
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: blacklist-tls
            hosts:
              - blacklist.polytech.apoorva64.com
    eck-operator:
      enabled: false