apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ollama-node-nino4
  namespace: ollama
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 60m
  chart:
    spec:
      chart: ollama
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: ollama
        namespace: ollama
      interval: 12h
  values:
    nodeSelector:
      # name of node
      kubernetes.io/hostname: node-nino4
    ollama:
      # If you want to use GPU, set it to true
      gpu:
        enabled: false
        number: 1
    persistentVolume:
      enabled: true
      storageClass: local-path
  # use nvidia containerRuntime
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
            patch: |
              - op: add
                path: /spec/template/spec/runtimeClassName
                value: nvidia
          - target:
              kind: Deployment
            patch: |
              - op: add
                path: spec/strategy
                value:
                  type: Recreate