apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ollama
  namespace: ollama
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 60m
  chart:
    spec:
      chart: ollama
      version: "0.6.0"
      sourceRef:
        kind: HelmRepository
        name: ollama
        namespace: ollama
      interval: 12h
  values:
    resources:
      requests:
        memory: 4096Mi
        cpu: 2000m
        nvidia.com/gpu: 1
      limits:
        memory: 8192Mi
        nvidia.com/gpu: 1
        cpu: 16000m
    nodeSelector:
      nvidia.com/gpu.product: NVIDIA-GeForce-RTX-2060-with-Max-Q-Design

    ollama:
      # If you want to use GPU, set it to true
      gpu:
        enabled: false
        number: 1
    persistentVolume:
      enabled: true
      storageClass: local-path
  # use nvidia containerRuntime
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
            patch: |
              - op: add
                path: /spec/template/spec/runtimeClassName
                value: nvidia

