apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ollama
  namespace: ollama
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 60m
  chart:
    spec:
      chart: ollama
      version: "0.5.0"
      sourceRef:
        kind: HelmRepository
        name: ollama
        namespace: ollama
      interval: 12h
  values:
    nodeSelector:
      kubernetes.io/arch: amd64
      k3s.io/hostname: node-apoorva2
    ollama:
      # If you want to use GPU, set it to true
      gpu:
        enabled: true
        number: 1
    persistentVolume:
      enabled: true
      storageClass: longhorn-single-replica
