apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ollama
  namespace: ollama
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 60m0s
  url: https://otwld.github.io/ollama-helm/
