apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release-node-volcano1.yaml
  - helm-release-node-volcano2.yaml
  - helm-release-node-apoorva2.yaml
  # - ollama-operator
