apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: langfuse
  namespace: langfuse
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 60m
  chart:
    spec:
      chart: langfuse
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: langfuse
        namespace: langfuse
      interval: 12h
  values:
    image:
      tag: 3.24
    postgresql:
      deploy: false
    langfuse:
      telemetryEnabled: False

      additionalEnv:
        # REDIS
        - name: "REDIS_CONNECTION_STRING"
          value: "redis://default:changeme@langfuse-valkey-primary:6379/0"
        # CLICKHOUSE
        - name: "CLICKHOUSE_MIGRATION_URL"
          value: "clickhouse://langfuse-clickhouse:9000"
        - name: "CLICKHOUSE_URL"
          value: "http://langfuse-clickhouse:8123"
        - name: "CLICKHOUSE_USER"
          value: "default"
        - name: "CLICKHOUSE_PASSWORD"
          value: "changeme"
        # S3 / MinIO
        - name: "LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID"
          valueFrom:
            secretKeyRef:
              name: langfuse-secret
              key: ACCESS_KEY_ID
        - name: "LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY"
          valueFrom:
            secretKeyRef:
              name: langfuse-secret
              key: ACCESS_SECRET_KEY
        - name: "LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT"
          value: "http://minio.ozeliurs.com:9000/"
        - name: "LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE"
          value: "true"
        - name: "LANGFUSE_S3_EVENT_UPLOAD_BUCKET"
          value: "langfuse"
        - name: "LANGFUSE_S3_EVENT_UPLOAD_REGION"
          value: "us-east-1"
        - name: "DATABASE_HOST"
          valueFrom:
            secretKeyRef:
              name: langfuse-db-app
              key: host
        - name: "DATABASE_PORT"
          valueFrom:
            secretKeyRef:
              name: langfuse-db-app
              key: port
        - name: "DATABASE_NAME"
          valueFrom:
            secretKeyRef:
              name: langfuse-db-app
              key: name
        - name: "DATABASE_USERNAME"
          valueFrom:
            secretKeyRef:
              name: langfuse-db-app
              key: username
        - name: "DATABASE_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: langfuse-db-app
              key: password
    minio:
      deploy: false

  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
            patch: |
              - op: add
                path: /spec/template/spec/dnsConfig
                value:
                  options:
                    - name: ndots
                      value: "1"
