kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-single-replica
provisioner: driver.longhorn.io
parameters:
  dataLocality: disabled
  fromBackup: ''
  fsType: ext4
  numberOfReplicas: '1'
  staleReplicaTimeout: '30'
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate