apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gpu-operator
  namespace: gpu-operator
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 60m
  chart:
    spec:
      chart: nvidia/gpu-operator
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: nvidia
        namespace: gpu-operator
      interval: 12h