# Service account the client will use to reset the statefulset,
# by default the pods running inside the cluster can do no such things.
kind: ServiceAccount
apiVersion: v1
metadata:
  name: statefulset-restart
  namespace: satisfactory
---
# allow getting status and patching only the one statefulset you want
# to restart
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: statefulset-restart
  namespace: satisfactory
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["statefulsets"]
    resourceNames: [""]
    verbs: ["get", "patch", "list", "watch"] # "list" and "watch" are only needed
    # if you want to use `rollout status`
