apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 60m
  chart:
    spec:
      chart: harbor
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: harbor
      interval: 12h
  values:
    externalURL: https://harbor.storage.apoorva64.com
    expose:
      ingress:
        hosts:
          core: harbor.storage.apoorva64.com
    persistence:
      persistentVolumeClaim:
        registry:
          storageClass: nfs-client
          size: 1Ti
        database:
          storageClass: longhorn-single-replica
        redis:
          storageClass: longhorn-single-replica
        trivy:
          storageClass: longhorn-single-replica
    portal:
      nodeSelector:
        kubernetes.io/hostname: node-apoorva2
    core:
      nodeSelector:
        kubernetes.io/hostname: node-apoorva2
    database:
      internal:
        nodeSelector:
          kubernetes.io/hostname: node-apoorva2