apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: isa-api-polytech
  namespace: isa-api-polytech
spec:
  interval: 5m
  path: ./manifests
  targetNamespace: isa-api-polytech
  serviceAccountName: flux-cd-base
  prune: true
  sourceRef:
    kind: GitRepository
    name: isa-api-polytech
    namespace: flux-system