apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ski-bank
  namespace: isa-api-polytech
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              io.kompose.service: bank
