apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: isa-api-polytech
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/pns-isa-devops/isa-devops-23-24-team-o-24
  ref:
    branch: jenkins
  secretRef:
    name: reporter-github-ozeliurs-auth