apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: sonarqube
spec:
  interval: 30m
  chart:
    spec:
      chart: postgresql
      version: "12.12.10"
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    global:
      postgresql:
        auth:
          username: dbusername
          password: dbpassword
          database: sonarqube