# role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flux-cd-base
  namespace: my-namespace
rules:
  - apiGroups:
      - ""
      - "apps"
      - "core"
      - "networking.k8s.io"
    resources: [ "*" ]
    verbs: [ "*" ]
