apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nfs-subdir-external-provisioner
  namespace: nfs-provisioner
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 60m0s
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/