apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-provisioner
  namespace: nfs-provisioner
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 60m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: nfs-provisioner
      interval: 12h
  values:
    nfs:
      server: 192.168.1.126
      path: /mnt/user/Home/apoorva
    nodeSelector:
      kubernetes.io/hostname: node-apoorva2