apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: nfs-provisioner
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client