apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  interval: 60m
  chart:
    spec:
      chart: redis
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 24h
  values:
    architecture: "standalone"
    auth:
      enabled: true
      existingSecret: redis-auth
    service:
      type: NodePort
      nodePorts:
        redis: 30001