---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-auth
  namespace: redis
spec:
  encryptedData:
    redis-password: AgDIb9kKsIQIwUaBOXK0c0DCLxZsMy8/I1shXCrhTeAFNP1yO35N5RqGBPxxl522bQC/7CKTClA3WGTfgYJ/fWk+p72bJKblBvubot5gTBwj1R45S9EgTe9XZe9SelIok6Z54Jn9f/dQPmgSxvK1g8ufQJLMBB2DB/b2BJNlN90p9rjFUclxE4S52Y6JZJln2wdJkQnwhpr444wz+pYivgYDRZYsIi4rCkGovaalzXfj0T+a5NpU/dReUvoT4dJURnt4fk+MDHq5aByvWflsNCyCreCYiiNGp9SUVNHz78UGirPWwys1ujdeYNLGg7dE94FKgRePGU1eCmiCL7qyb5+iLzZezECPq8nD/hrlhMqW0AR6yTtzBdpoCjgbBWVGYHb0IC1zxHJE2EnDhNYOvpcOQe60oT+OHf6yUw4KK1F7QRxqgMo/kyHYhSUYDV5995Vnz3tCfT+PZXKKguBgCbeWTz731ZwK4ts6f5p0wlG6RZEHi+Opu1L5KFcssofB36ZUU8tgKQGvPY2LEAKLmxL5zY66weus8SH3pdQvkgLM6qnzNzLnLTIT30bdE8Aw+ZDZ3To/WR0EmE4G4jF63nmyL0IVzRdpRFNgIHwOeq5lcW+9XYBg9/KM04EK5rMpoXo7S+nMVC1oNZrU1j/9C+C7zz8quPohTyqTzGIuBYiOHqCTX7wqvyFAQGvxvJBAMR54xZxA70asEizCE51MnnfXiUOAFF1qsZtkC8g2dw==
  template:
    metadata:
      creationTimestamp: null
      name: redis-auth
      namespace: redis
