apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: satellite-api-react-flight-tracker
spec:
  path: ./manifests/overlays/develop
  targetNamespace: satellite-api-react-flight-tracker-dev
