apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../../base/satellite-api-react-flight-tracker

namespace: satellite-api-react-flight-tracker-dev
patchesStrategicMerge:
  # patch repository to reference to develop branch
  - repository-patch.yaml
  # patch kustomize to reference to develop manifests
  - kustomize-patch.yaml