apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: potatobank
  namespace: potatobank
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: ghcr.io/startupnationlabs/potatobank:sha-778f3b2d67dd9a7bcedda6296f70be7ec88197c0
          ports:
            - containerPort: 8000
