apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: keycloak
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 60m
  chart:
    spec:
      chart: keycloak-operator
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: keycloak-operator
        namespace: keycloak
      interval: 12h
