apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio-main
spec:
  interval: 60m
  chart:
    spec:
      chart: minio
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 12h
  values:
    mode: distributed
    replicas: 4
    persistence:
      storageClass: nfs-client
    nodeSelector:
      kubernetes.io/arch: amd64
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: minio
            app.kubernetes.io/instance: minio
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
      hostname: 'minio.storage.apoorva64.com'
      path: /
      tls:
        - hosts:
            - minio.storage.apoorva64.com
          secretName: minio-tls
    apiIngress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
      hostname: 'api.minio.storage.apoorva64.com'
      path: /
      tls:
        - hosts:
            - api.minio.storage.apoorva64.com
          secretName: api-minio-tls
    extraEnvVars:
      - name: MINIO_PROMETHEUS_URL
        value: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
      - name: MINIO_PROMETHEUS_JOB_ID
        value: "minio-main"
      - name: MINIO_PROMETHEUS_AUTH_TYPE
        value: "public"
    securityContext:
      enabled: true
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
      fsGroupChangePolicy: "OnRootMismatch"

    auth:
      existingSecret: minio-auth