apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: password-generator
  namespace: password-generator
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/startupnationlabs/pswd/api:main
          ports:
            - containerPort: 8080