apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-forward-auth
  namespace: kube-system
data:
  INSECURE_COOKIE: 'false'
  COOKIE_DOMAIN: apoorva64.com
  DOMAINS: apoorva64.com
  AUTH_HOST: forward-auth.auth.apoorva64.com
  URL_PATH: /_oauth
  DEFAULT_PROVIDER: oidc
  PROVIDERS_OIDC_ISSUER_URL: https://keycloak.auth.apoorva64.com/realms/lab
  PROVIDERS_OIDC_CLIENT_ID: traefik-forward-auth