apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-forward-auth
  namespace: kube-ray
spec:
  forwardAuth:
    address: https://forward-auth.auth.apoorva64.com/
    trustForwardHeader: true
    authResponseHeaders:
      - X-Forwarded-User