apiVersion: v1
kind: Secret
metadata:
  name: traefik-forward-auth
  namespace: kube-system
data:
  PROVIDERS_OIDC_CLIENT_SECRET: <base64 encoded client secret>
  SECRET: <base64 encoded secret>
type: Opaque
