apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: starboard
  namespace: starboard
spec:
  interval: 60m
  chart:
    spec:
      chart: starboard
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: aqua
        namespace: flux-system
      interval: 12h
