apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: react-flight-tracker-dev
  namespace: react-flight-tracker
spec:
  interval: 5m
  path: ./manifests/react-flight-tracker/overlays/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: react-flight-tracker