apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: react-flight-tracker
  namespace: react-flight-tracker
spec:
  interval: 5m
  url: https://gitlab.com/dev6645326/react-flight-tracker
  ref:
    branch: master