apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: react-flight-tracker
  namespace: flux-system
spec:
  interval: 5m
  url: https://gitlab.com/dev6645326/react-flight-tracker
  ref:
    branch: master
  secretRef:
    name: gitlab-auth