---
apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
  labels:
      toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.bitnami.com/bitnami


---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 30m
  chart:
    spec:
      chart: oci://registry-1.docker.io/bitnamicharts/keycloak
      version: "18.x"
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd

      hosts:
        - host: keycloak.apoorva64.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: keycloak-tls
          hosts:
            - keycloak.apoorva64.com

