---
apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: codecentric
  namespace: flux-system
spec:
  interval: 24h
  url: https://codecentric.github.io/helm-charts


---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak-postgresql
  namespace: keycloak
spec:
  interval: 30m
  chart:
    spec:
      chart: postgresql
      version: "*"
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    global:
      postgresql:
        auth:
          username: dbusername
          password: dbpassword
          database: keycloak
          replicationPassword: replication-password
    architecture: replication
    replication:
      synchronousCommit: "on"
      numSynchronousReplicas: 1
      applicationName: keycloak-postgresql
    readReplicas:
      replicaCount: 2
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 30m
  chart:
    spec:
      chart: keycloakx
      version: "*"
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: codecentric
        namespace: flux-system
  install:
    remediation:
      retries: 2
  values:
    replicaCount: 3
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
      rules:
        - # Ingress host
          host: 'keycloak.auth.apoorva64.com'
          # Paths for the host
          paths:
            - path: '{{ tpl .Values.http.relativePath $ | trimSuffix "/" }}/'
              pathType: Prefix
      tls:
        - hosts:
            - keycloak.auth.apoorva64.com
          secretName: keycloak-tls
    command:
      - "/opt/keycloak/bin/kc.sh"
      - "--verbose"
      - "start"
      - "--http-enabled=true"
      - "--http-port=8080"
      - "--hostname-strict=false"
      - "--hostname-strict-https=false"
      - "--spi-events-listener-jboss-logging-success-level=info"
      - "--spi-events-listener-jboss-logging-error-level=warn"

    extraEnv: |
      - name: KEYCLOAK_ADMIN
        valueFrom:
          secretKeyRef:
            name: {{ include "keycloak.fullname" . }}-admin-creds
            key: user
      - name: KEYCLOAK_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: {{ include "keycloak.fullname" . }}-admin-creds
            key: password
      - name: JAVA_OPTS_APPEND
        value: >-
          -XX:+UseContainerSupport
          -XX:MaxRAMPercentage=50.0
          -Djava.awt.headless=true
          -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless

    dbchecker:
      enabled: true

    database:
      vendor: postgres
      hostname: keycloak-postgresql-primary.keycloak.svc.cluster.local
      port: 5432
      username: dbusername
      password: dbpassword
      database: keycloak