---
apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
  labels:
      toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: codecentric
  namespace: flux-system
spec:
  interval: 24h
  url: https://codecentric.github.io/helm-charts


---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 30m
  chart:
    spec:
      chart: keycloakx
      version: "*"
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: codecentric
        namespace: flux-system

