---
apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
  labels:
      toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: codecentric
  namespace: flux-system
spec:
  interval: 24h
  url: https://codecentric.github.io/helm-charts


---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 30m
  chart:
    spec:
      chart: keycloakx
      version: "*"
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: codecentric
        namespace: flux-system
  values:
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd

      rules:
        - host: keycloak.apoorva64.com
      tls:
        - secretName: keycloak-tls
          hosts:
            - keycloak.apoorva64.com
    command:
      - "/opt/keycloak/bin/kc.sh"
      - "start"
      - "--http-enabled=true"
      - "--http-port=8080"
      - "--hostname-strict=false"
      - "--hostname-strict-https=false"
    extraEnv: |
      - name: KEYCLOAK_ADMIN
        value: admin
      - name: KEYCLOAK_ADMIN_PASSWORD
        value: admin
      - name: JAVA_OPTS_APPEND
        value: >-
          -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless

