apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ../../base/si4-ml-digits-recognition
namePrefix: prod-

patches:
  - target:
      kind: Kustomization
      name: react-flight-tracker
    path: kustomize-patch.yaml