apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: simple-ollama-operator-crds
  namespace: flux-system
spec:
  interval: 5m
  path: ./config/crd
  prune: true
  sourceRef:
    kind: GitRepository
    name: simple-ollama-operator