apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: <base64-encoded-string>
  AWS_SECRET_ACCESS_KEY: <base64-encoded-string>
  AWS_ENDPOINTS: <base64-encoded-string>