apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: langfuse
  namespace: open-webui
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 60m0s
  url: https://langfuse.github.io/langfuse-k8s
