---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: langfuse-secret
  namespace: langfuse
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBFxnnMgCpILm5Rn4YkHYQ+b6LOrg/pu5+8hWVM2Qp0HTp5KvUVFVx9wWQy07yE9XiBnkbfhoxoYgYavvhLW+XZJ7XNB3Bx6mwIIhsWUkrPNo+J2RhACa44tO9kHP7VbjQ3B1JurArbrr72UxCSZvehIu2jgboZU276icsCpdC0x2wkzQ3ErsbbdIK2zklFD0PpA0vwOXsy3WiXDsLMgat0MV2BNDPL4VGFKCMSvEP39iDpBWnkGXZ1BVPQUWm45n7wbXyrErtNQVtsks83lRUtg0CTJAFkX1uGLCVDJ9z7oDkmWMqhof30USv6FTjUATeV2QL4UOagQ0g8TQY+sw/QR4BFu4ARA9ShYWdY01MdSuCteU3F+NIvwCNdihh4/4n0BMWMjs+9aeRrRom2xE1pQVbG6Dl9f6IIYwL0DY8fueGH7f3YdoIc48AaXlb4kDixTVNZ6JWD2adjPJDtju3013665BBHa9Mvcrk37me/TINocHgwMaTDurha4Mr/+xVH5afUr/nZtXDyDVoNRGWoO6u+GGs7cIr3nXN7ER8XbP5yzqnqvEO6rXMWK8p3jyzkxwyzYsGjuk0mZISZOipGcdJdxUY2sYpVZjK55odHO25ZhaAt8btkfHEsqYXm2MA7UfjGxexN4rJ60Oohx8LEwJly+vIMWQjcoMdoEp5ccP8CyXYU27suMEEQB1OWaL5lVyz7GnlY0tLYQKjKHgB0uqOvBg==
    ACCESS_SECRET_KEY: AgCSx4cMFOpcD9rcMsUcDNbu9oiyjQ5fWAKswujbAGR8M/dGa6yhyErZQdiAz4ffwTciq7D+mskVi8zUbYrp/MIaq7BK2zyMhJ8zq0C8DteVNCftBPYGzXJlbdcXJ/yZOXhAbn4qGEt0tJ14QU83T2fb24lm8xMU7xi5svZZZX60FJqSecR1WcohGlaVUssrZ4I6AbzW2xP5+ngtaW/40B9m25OFEKXMx0alW9gx2nk1EPiM1UVe9atxxCsJFI2LrzMwHa0RirKPAWwdylVkLIF/zuD5LTkhYipVbVVFxL/12JZcEB9O9IQ4RIpfA0Z1JUkYum5b2YKghWXmMTravCG+WWOi1XUgUxZkUci4Trj4Jf0p4BpzVUD+Cr6++RtT8trc+AWHgsLNuu1nN1qI8eoqQGmGJvx6eH3aWjjOSI/lIYpzg9I0rnn+V18MZpvOTdJu81yZ8e1TBe4K6Qtt5VEpQXHRwQcjTbnGyuKoB9UMz6Q4hbkS2kxzhqhvZKztnqrj/yDo7jmzyYGiEkTV+8px9govhMtLOQlJmUdtffCx5On5gn1YkjErAY+Bk/XP1kVQAFCH70Cf45bN6UcCYc5J9Kh7z5EkDis5LdjbgOWXbql7nMnWm8iF1AadIWMqw43/UvxYiVUgTRmJB0+imgohmbJ4Nnt0zvs5koIPtHqBofMB0Tlx1g03IolrgRsAVuGzHgyIWxryrQuWQANl4fB4g0jDEbEKiyFTShrBC2kCFvTvLxXM9M4A
  template:
    metadata:
      creationTimestamp: null
      name: langfuse-secret
      namespace: langfuse
    type: Opaque
