apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - istio
  - kali
  - https://raw.githubusercontent.com/istio/istio/release-1.23/samples/addons/extras/zipkin.yaml
  - tempo
