---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-s3-access
  namespace: harbor
spec:
  encryptedData:
    harbor-s3-values.yaml: AgCWpxg2qwHsyIGkuny1SevdQL5k8bvT4ro5kUyBGUHHc10RZfPkQVvqnCYTqCzDBg85j2IBG3kUktnbFhA/2AzLTwO6kwOi5+82M2LgIEDpkne+dwqjRsgMM6/peS7yqpXaRG78QNj4L4B31bys0bq9s4XifGZWFQ4jMvjPQWbFmzrFSpqVmEh0KUMPWEvMOJJbBQWZzxCm1xqFdX56nvmUwIYK4O9km6gLON7URQpNzYE3hPAzGH9wgoRnC5uz7RZMynDASBx8BntZvLLeX8wKsEb18iP9b+5XIxADWQctBD5HGBP6sxxDCbevKXM61njaFerm162E7u59B80OboVVnCJq1sNwiHq29Gb4a+vgxpFaLu20/zn74DbZNomcOexyDRzKnVEY68RUEfWLJNdclasJHwaoW0h4nEwVGCkt82n2NufShFcl0iDCA48/RqH07Rfg5thMG1L35rwHRR5WOrqrZWlJlZhkOpIgRjxgpR7ty+i0aKGbeDPPmXTPPFz+xjJNU7Sup5meIBz6SnAQOxiMKtVzmKgYgvMV/NB5uQ1BzFq0b9+AZsrXhhibECX3ZdjzfyoznUZyBEQl6ny6mQNuZMXuoYXBL9GjC2ORg0vQ3kBcwwVeVFzIP5PbQdmTufCYZFBDghUccLJybCrVYVpV/6Y1TvFe9NmAAA5oP6XgR7iLf3cvq60MdGWHg+P176BcARzWJRPRqY7oMC1twVdcaeCbTyRZ8ixxvZiR9hw0Y5SE5SsLhz/u0+jkavpYCSEXSwmOfOISQYbIG7X2c1jqVa3/FekkDLC7dJlJbWcs9OzUhod6gbAYaiseeaCPAApXi0jtH5KWCodgFppdAaroSQzNtZRuKUcuHDVOgfHwbeZiVYF4Gg+8bbDNB7vrFRYXiCjAlj2hirjZgJHneGC2R82GYg4Hct8frg==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-s3-access
      namespace: harbor
