apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kserve-crd
  namespace: kserve
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 60m
  chart:
    spec:
      chart: kserve-crd
      version: "0.14.1"
      sourceRef:
        kind: HelmRepository
        name: kserve-charts
        namespace: kserve
      interval: 12h
  values:
    nodeSelector:
      kubernetes.io/arch: amd64