---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: satisfactory
  namespace: satisfactory
spec:
  selector:
    matchLabels:
      app: satisfactory
  serviceName: "satisfactory"
  replicas: 1
  template:

    metadata:
      labels:
        app: satisfactory
    spec:
      nodeSelector:
        "kubernetes.io/hostname": "node-apoorva3"
      automountServiceAccountToken: false
      containers:
        - name: satisfactory
          image: wolveix/satisfactory-server:latest
          env:
            - name: DEBUG
              value: "false"
            - name: MAXPLAYERS
              value: "8"
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: SKIPUPDATE
              value: "false"
            - name: STEAMBETA
              value: "false"
            - name: SERVERBEACONPORT
              value: "27010"
            - name: SERVERGAMEPORT
              value: "27011"
            - name: SERVERQUERYPORT
              value: "27012"
          ports:
            - containerPort: 27012
              name: "query"
              protocol: UDP
            - containerPort: 27010
              name: "beacon"
              protocol: UDP
            - containerPort: 27011
              name: "game"
              protocol: UDP
          volumeMounts:
            - name: satisfactory-data
              mountPath: /config
  volumeClaimTemplates:
    - metadata:
        name: satisfactory-data-3
      spec:
        storageClassName: local-path
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 20Gi