---
apiVersion: v1
kind: Service
metadata:
  name: satisfactory
  namespace: satisfactory
  labels:
    app: satisfactory
spec:
  type: NodePort
  ports:
    - port: 27011
      nodePort: 27011
      protocol: UDP
      name: "gameudp"
      targetPort: "gameudp"
    - port: 27011
      nodePort: 27011
      protocol: TCP
      name: "gametcp"
      targetPort: "gametcp"
    - port: 27012
      nodePort: 27012
      protocol: TCP
      name: "gametcpnew"
      targetPort: "gametcpnew"
  selector:
    app: satisfactory