---
apiVersion: v1
kind: Service
metadata:
  name: satisfactory
  namespace: satisfactory
  labels:
    app: satisfactory
spec:
  type: NodePort
  ports:
    - port: 27012
      nodePort: 27012
      protocol: UDP
      name: "query"
      targetPort: "query"
    - port: 27010
      nodePort: 27010
      protocol: UDP
      name: "beacon"
      targetPort: "beacon"
    - port: 27011
      nodePort: 27011
      protocol: UDP
      name: "game"
      targetPort: "game"
  selector:
    app: satisfactory