---
apiVersion: v1
kind: Service
metadata:
  name: satisfactory
  namespace: satisfactory
  labels:
    app: satisfactory
spec:
  type: NodePort
  ports:
    - port: 27011
      nodePort: 27011
      protocol: UDP
      name: "game-udp"
      targetPort: "game"
    - port: 27011
      nodePort: 27011
      protocol: TCP
      name: "game-tcp"
      targetPort: "game"
  selector:
    app: satisfactory