apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor-database-postgres
  namespace: harbor
spec:
  interval: 60m
  chart:
    spec:
      chart: postgresql
      version: "14.3.3"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 24h
  values:

    persistence:
      storageClass: longhorn-single-replica
      size: 8Gi

    global:
      postgresql:
        existingSecret: harbor-database-postgresql

