apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zookeeper-operator
  namespace: stackable-operators
spec:
  interval: 60m
  chart:
    spec:
      chart: zookeeper-operator
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: stackable-stable
        namespace: stackable-operators
      interval: 24h
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hdfs-operator
  namespace: stackable-operators
spec:
  interval: 60m
  chart:
    spec:
      chart: hdfs-operator
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: stackable-stable
        namespace: stackable-operators
      interval: 24h
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: commons-operator
  namespace: stackable-operators
spec:
  interval: 60m
  chart:
    spec:
      chart: commons-operator
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: stackable-stable
        namespace: stackable-operators
      interval: 24h
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secret-operator
  namespace: stackable-operators
spec:
  interval: 60m
  chart:
    spec:
      chart: secret-operator
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: stackable-stable
        namespace: stackable-operators
      interval: 24h
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: listener-operator
  namespace: stackable-operators
spec:
  interval: 60m
  chart:
    spec:
      chart: listener-operator
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: stackable-stable
        namespace: stackable-operators
      interval: 24h
