apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 60m
  chart:
    spec:
      chart: gateway
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 12h
  values:
    service:
      type: NodePort
      ports:
        - name: http2
          nodePort: 28001
          protocol: TCP
          targetPort: 80
          port: 80
        - name: https
          nodePort: 28002
          protocol: TCP
          targetPort: 443
          port: 443