apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-istiod
  namespace: istio-system
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 60m
  chart:
    spec:
      chart: istiod
      version: 1.26.4
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 12h
  values:
    global:
      proxy:
        tracer: zipkin
    meshConfig:
      extensionProviders: # The following content defines two example tracing providers.
        - name: "localtrace"
          zipkin:
            service: "zipkin.istio-system.svc.cluster.local"
            port: 9411
            maxTagLength: 56