apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: spos-backend
  namespace: spos-prod
spec:
  interval: 5m
  targetNamespace: spos-prod
  path: ./manifests
  prune: true
  serviceAccountName: flux-cd-base
  sourceRef:
    kind: GitRepository
    name: spos-backend
  patches:
    # prefer amd64 nodes
    - target:
        kind: Deployment
      patch: |-
        - op: add
          path: /spec/template/spec/nodeSelector
          value:
              kubernetes.io/arch: amd64