apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: raycluster
  namespace: kube-ray
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 60m
  chart:
    spec:
      chart: raycluster
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: kuberay
        namespace: kube-ray
      interval: 12h
  values:
    image.tag: nightly-aarch64
