apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ray-cluster
  namespace: kube-ray
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 60m
  chart:
    spec:
      chart: ray-cluster
      version: "0.6.0"
      sourceRef:
        kind: HelmRepository
        name: kuberay
        namespace: kube-ray
      interval: 12h
  values:
    image:
      repository: apoorva64/ray-w-deps
      tag: latest
    worker:
      resources:
        limits:
          cpu: "4"
          memory: "12G"
        requests:
          cpu: "1"
          memory: "8G"
    head:
      resources:
        limits:
          cpu: "4"
          memory: "12G"
        requests:
          cpu: "1"
          memory: "8G"