apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ray-serve
  namespace: kube-ray
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ray-serve.kube-ray.apoorva64.com`)
      kind: Rule
      services:
        - name: ray-serve
          port: 8000
          namespace: kube-ray
  tls:
    secretName: ray-serve-tls-ingress