apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ray-serve
  namespace: kube-ray
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`ray-serve.ray.apoorva64.com`)
      services:
        - name: ray-serve
          port: 8000
  tls:
    secretName: ray-serve-tls-ingress