apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actions-runner-controller
  namespace: arc-systems
spec:
  interval: 60m
  chart:
    spec:
      chart: gha-runner-scale-set-controller
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
      interval: 12h