apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: camping
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch"]