apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-only
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["*"]
    verbs: ["get", "list", "watch"]