apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kali
  namespace: istio-system
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 60m0s
  url: https://kiali.org/helm-charts