apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali-server
  namespace: istio-system
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 60m
  chart:
    spec:
      chart: kiali-server
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: kali
      interval: 12h
  values:
    auth:
      strategy: "anonymous"
    external_services:
      prometheus:
        url: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"