---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kiali
  namespace: istio-system
spec:
  encryptedData:
    oidc-secret: AgAmHzWsVfNXdOiCCfl+RAIUBJZgZ9/DhKXfqscxcgM7VVKuD9G9uAEyW5DhVP3nyFi1Ng7edyfxiYEACyGDjh7BALThGJ7Q+mh8L80Y5EaJcuYKWVT0Pn7vIBOD+0RGT/LijJTGvqddPAO8ebdEOy4/sPau5UDe2l/oZ45VEYnEksDor3NYFUysNtZlUD0JIPAKSTFSJ4lCal3DjXj1VHFJEn2XDpZM9iTK4X1vn1fAySNhpDmOPiCPDibMcEXPUF8Yz/JQz7hUrKItoRNNsVAbwbUZfCNQrM24eScoUrMGfc09N8qp0OHfZBTnlMxrxfPUhMRNnQPz8ePkkPwjA3HCHelhrH/yBgQGkSv4cpi2jwgV+U+KyUxgV/JZIBDJauTgVNJLTtb+hMx3B/DDOZbqy7zfRIyNUXKcZ6bjvXZ2VSDRN1VL+zTTxZDysQsTWKBhaJp9Flk5Vjd2YPMBvz+eqqqe3PTSeLkPzhBnRVOpW9l1ijASzJPHqaeVS/PKy35rVuGCfh7kmtS1dW0Vm4L/aGNgwweq5teMZBIaZyqC1GY7ga0dgWJTtxEKmNx/xA/F3pTOvBnj0FQpAGRJWfBz9D2WgwmtjcwMyf70CpgvV6JmpP6fcgyVLsw0YBt0VZd+wQKDMWeSq3+mduU8QMil+rLORUN0boYAxq2e1ClqLPtKtXJ0l1LRsLCN/Inbtit4hxv9Wt5I0ChgAnghRDaF1cZyFiOEBne3KRda+n8WIA==
  template:
    metadata:
      creationTimestamp: null
      name: kiali
      namespace: istio-system
