---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kiali
  namespace: istio-system
spec:
  encryptedData:
    oidc-secret: AgAkTK8RKB1uV3iJ9OP+kk4HT426uZ0vvNQhdoDvaQFzY7QVKd0tskIql4H1gBYJWR3DSmrhp6ZbfkS5+ka6fsFBgASeKSYkaSvkkjqIH6y0HClOX0HQZVwcQ57fmmd03hd5bwi/SkLbeY5Idr0AsJJAbDO3b7CQxoRnSk1mdtfr0NNAHOYQ90XDQGSCFk/k75ifa33ocKaq2gkJ6V9IbJgNcQ6CrbSUR6wI1tpz/c7Qns0+UE0mq5xvG4y0v6XXhywk2fkgni9SMfGHDxQ2Jc10xsi8hXkA2sGOs2LG1w00/pCc1iL0yUrYFcfeEQv2wfPtXh+YqURczjGAcApwUNQxm/2Sb6QCtH+7MhxdZ8REDTwEHtYQd2isddUv23LtjLHN1JL5uQvjMBVP1MRk9EeDxqsmzZDKL4Fm/WWV0EiIlc6NYu7OfAPFtJvztrn5TZBRLF9jBzrJOigNmylVatw1aUnN1IS/txce4FT708OYERFTct/WhWvTuIJGJVeQpwI8zIb5fJso8dSxpZFcW+LwWi3m7Y8nv/nGJoDC07ss3/vGFxrw9m91sBrn6ZoBwMfMESIxVd4MBiMhO2ABxoSBMdB6NfpJVhkdBAfadnvY5xHxOiXQ0n35PyBJN9sJqm9puEgLVBMxvyREHMN5MM1RhCYSm8ae8UzwZpkv9BY+6dDTvhVczu4o9I8QNjK5WgtCg4X94vVjMCg+9oREZlY4a7exaFtgxuVcRV01ESoKKA==
  template:
    metadata:
      creationTimestamp: null
      name: kiali
      namespace: istio-system
