---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kiali
  namespace: istio-system
spec:
  encryptedData:
    oidc-secret: AgB7srAWRe6UBq3qv5fpTKlRIsaz+Pcm5n568hUkukyR7w+Yjd4FDE0UxMAtcOX6WzRYbUWEm3wO41wfS9a3RJ+TvMXpOSk1/BZPv/Uh37bGQ7vhZnjzh3wnhgIX2UEQYPlKDKBSeMCVYU3srrA6CgYDm4jutAKyUDeqxF5LLkESQldPWBS7ZTWfEVfGL075vByn9Bj2mAXhyKKzDRS+MWMxhpewn7K/aoAYoCVFJ6IG3eBRHDIZfjUPts9RNf7AgqK8SI7ILttOsiIK+VmGplQyN5mkH0UI/fRO4qJAGkwU0REVtJrcBuuJH5/7WbZYWFobps0U0MWI0EfJVjHIIV74QFgPPbokffpAysu1ItdAUdPiwxWhJ1Hf+F79fqWlZPG+nFKnMBojVy7HKSTAl7WBQUcp6Ma5alGZxPnPwG8doZi6jm/9hWZvGrxjh3y75PAUAA074L9n/Cqlze/HY1msONsTox82jLaIqsWh38l9PxNvqjyGm4ya0u2C7x4qlmJGufXHyH1al8XMTshTcqWZ0PPvUdK0m1vcduNCYFQoOHr2dH3cmlSDGYzdPnx1mjqRf44GnTjtQtVbug0Lt1eR+2/kDvc5cs2ZhoyfhF6M2U+DerXmk64z5AppSKjCgmzt1vvior9zzKxchGEEPJbtB/16SgfAKwVq51hLP7yl4rVgScSoohxQtnkyFCGHnPbHCVdJshQCFnzD5jIYTjcAy/3G6RnndhHtGLi7Fhe4sw==
  template:
    metadata:
      creationTimestamp: null
      name: kiali
      namespace: istio-system
