apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release-server.yaml
  - helm-release-istiod.yaml
