apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: network-check
  namespace: flux-system
spec:
  interval: 5m
  path: ./manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: network-check
  images:
    - name: ghcr.io/apoorva64/network-check/network-check
      newTag: cc56a671c63d93bb46abd0f70751a38a647ed5dc