apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: network-check
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/Apoorva64/network-check
  ref:
    branch: master