apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: emiliemasse
  namespace: emiliemasse
spec:
  template:
    spec:
      containers:
        - image: hugo971/emiliemasse:v1.0
          ports:
            - containerPort: 80
              protocol: TCP
          readinessProbe:
            successThreshold: 1
            tcpSocket:
              port: 80
