apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: eternity2-grpc
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: ghcr.io/startupnationlabs/eternity2/grpc-server:latest
          name: grpc-server
          resources:
            limits:
              cpu: "6"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "512Mi"
          ports:
            - containerPort: 50051
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: frontend
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: ghcr.io/startupnationlabs/eternity2/frontend:latest
          name: frontend
          env:
            - name: SERVER_BASE_URL
              value: https://eternity2-grpc.knative.apoorva64.com
          ports:
            - containerPort: 80
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: envoy
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: ghcr.io/startupnationlabs/eternity2/envoy:latest
          name: envoy
          env:
            - name: SOLVER_API
              value: http://eternity2-grpc
          ports:
            - containerPort: 50052