apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: eternity2-grpc
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: ghcr.io/startupnationlabs/eternity2/grpc-server:latest
          name: grpc-server
          resources:
            limits:
              cpu: "6"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "512Mi"
          ports:
            - containerPort: 50051
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: frontend
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: ghcr.io/startupnationlabs/eternity2/frontend:latest
          name: frontend
          env:
            - name: SERVER_BASE_URL
              value: https://envoy.knative.apoorva64.com
          ports:
            - containerPort: 80
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: envoy
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: ghcr.io/startupnationlabs/eternity2/envoy@sha256:faf9f62e4af5c9986092fad2bfc60ecb1f1b5a768f7dc99e355fe3fb1d38bcec
          name: envoy
          env:
            - name: SOLVER_API
              value: eternity2-grpc
          ports:
            - containerPort: 50052