apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-node-apoorva2-pvc
  annotations:
    volume.beta.kubernetes.io/storage-path: "/mnt/ollama"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 64Gi
