apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - letsencrypt-issuer-production.yaml
  - letsencrypt-issuer-staging.yaml
  - traefik-https-redirect-middleware.yaml
  - gitlab-auth-sealed.yaml