apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: open-webui
resources:
  - namespace.yaml

  - openwebui/pvc.yaml
  - openwebui/service.yaml
  - openwebui/ingress.yaml
  - openwebui/deployment.yaml

  - openwebui-db/postgres.yaml
  - openwebui-db/sealed-secret.yaml

  - openwebui-pipelines/service.yaml
  - openwebui-pipelines/deployment.yaml
  - openwebui-pipelines/pvc.yaml
  - openwebui-pipelines/sealed-secret.yaml
