apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: open-webui
resources:
  - namespace.yaml
  - webui-pvc.yaml
  - webui-service.yaml
  - ingress.yaml
  - deployment.yaml
  - postgres.yaml