apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: camping
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/neoteristis/origin-api
  ref:
    branch: main
  secretRef:
    name: raph-github-auth2