apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 60m
  chart:
    spec:
      chart: loki
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 12h
  values:
    loki:
      storage:
        type: "s3"
        s3:
          region: eu-central-1
          endpoint: "minio.storage.svc.cluster.local:9000"
          insecure: true
          s3ForcePathStyle: true
        bucketNames:
          chunks: loki-chunks
          ruler: loki-ruler
          admin: loki-admin
    backend:
      replicas: 2
    read:
      replicas: 2
    write:
      replicas: 2
    monitoring:
      serviceMonitor:
        labels:
          release: kube-prometheus-stack


  valuesFrom:
    - kind: Secret
      name: loki-s3-access
      valuesKey: loki-s3-values.yaml