apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 60m
  chart:
    spec:
      chart: loki
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 12h
  values:
    write:
      persistence:
        storageClass: "longhorn-single-replica"
    read:
      persistence:
        storageClass: "longhorn-single-replica"
    backend:
      persistence:
        storageClass: "longhorn-single-replica"
    singleBinary:
      persistence:
        storageClass: "longhorn-single-replica"
    loki:
      storage:
        type: "s3"
        s3:
          region: eu-central-1
          endpoint: "minio.minio-main.svc.cluster.local:9000"
          insecure: true
          s3ForcePathStyle: true
        bucketNames:
          chunks: loki-chunks
          ruler: loki-ruler
          admin: loki-admin
        storage_config:
          aws:
            s3: "s3://loki-chunks"
      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: aws
            object_store: aws
            schema: v11
            index:
              prefix: loki_index_
              period: 24h
    deploymentMode: SimpleScalable
    monitoring:
      serviceMonitor:
        labels:
          release: kube-prometheus-stack
    limits_config:
      retention_period: 96h
  valuesFrom:
    - kind: Secret
      name: loki-s3-access
      valuesKey: loki-s3-values.yaml