apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poulet
  namespace: poulet
spec:
  interval: 60m
  chart:
    spec:
      chart: poulet
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: poulet
      interval: 12h
  values:
    grafana:
      enabled: false
      ingress:
        enabled: true
        hosts:
          - grafana.al.apoorva64.com
    # This is to override the chart name.
    nameOverride: ""
    fullnameOverride: ""
    prometheus:
      enabled: false
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
          cert-manager.io/cluster-issuer: letsencrypt-prod
          traefik.ingress.kubernetes.io/router.middlewares: poulet-prometheus-basic-auth@kubernetescrd
        hosts:
          - host: prometheus.al.apoorva64.com
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls:
          - secretName: prometheus-al-apoorva64-com-tls
            hosts:
              - prometheus.al.apoorva64.com

      alertmanager:
        enabled: false
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
          limits:
            memory: "400Mi"
            cpu: "400m"
      kube-state-metrics:
        enabled: false
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
          limits:
            memory: "400Mi"
            cpu: "400m"
      prometheus-node-exporter:
        enabled: false
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
          limits:
            memory: "400Mi"
            cpu: "400m"
      prometheus-pushgateway:
        enabled: false
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
          limits:
            memory: "400Mi"
            cpu: "400m"
      server:
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
        persistentVolume:
          storageClass: local-path
          size: 15Gi

        extraArgs:
          web.enable-remote-write-receiver: null
        #  - secretName: chart-example-tls
        #    hosts:
        #      - chart-example.local


      configmapReload:
        prometheus:
          resources:
            requests:
              memory: "100Mi"
              cpu: "200m"
            limits:
              memory: "400Mi"
              cpu: "400m"
    keycloak:
      enabled: true
      proxy: edge
      auth:
        adminUser: admin
        existingSecret: keycloak-secret
        passwordSecretKey: password
      postgresql:
        auth:
          existingSecret: keycloak-postgresql-secret
          secretKeys:
            adminPasswordKey: postgresql-password
            replicationPasswordKey: replication-password
            userPasswordKey: user-password
      ingress:
        enabled: false
        hostname: keycloak.al.apoorva64.com

    alert-management:
      enabled: false
    mongodb:
      enabled: false
    patient-management:
      enabled: false
