---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgresql-secret
  namespace: poulet
spec:
  encryptedData:
    password: AgAcRP0XVmCM7h88vV3vJRALbpYtzkL66exLbZP3EZ3HLz+N6erUuLp5fgkzF39pnSpEyw/DD6SkN3/v1rClMaM90GqRi68y3oin26kk4Fm9bb4OvuB8OStbk92CAMZyZxoRFtAOCOOCYuSsd+XvDefLcycgd1rrV+3tihv860eXVRdMF86sieEzYlm2BUGhtroHM2ib7/DiDTT5hmy2WQfZlFcC+lFnaNLo7/yyCWKuztdn0DwSd1r4LSAZpc0/eg46IaBmRyahRjEYERj7iBIZ2z4XRAFg3apMjsBOsRQ+ktyp15aRwU9ll1+rou+WqXnRmKkdDpYaJxdflAF302EYtrTKlGeLJXQhU0a/kciK4v9CXLzfKBwrtM6UH2J3QHDC6aAbQU8+sgKKPgKidcSM4T2CtgJ8y4CR3JSV3ttzcnKFNuZWXFHpEzb+84u5zsDs2I6Mmotri5LtjuKuP7HVvpj6acOayrvljzeW6+X5py9OpCreUEpfr9eoQUBUg1Uo7+SFK/pcABOXQRSbg2Lq7wF3aJvrXLw2QZEN0HaYbT8R4mONIZNkjWLqwFXCEWhGkLn/cLHf6jZ5zsOj+B/ea1pIe8xuknIlYfw9UAiB8gYH59F0rXdzNFtNpOocgRQAomKQbUQwukxJZvo6EJtj0QtJ1VgW6ioooGva0SVskqRX0LzAkm1W/otKZbsMPCeEBYFkh+SdSUCwJa3K7qKeC/AFhpW8sKqy1T78E0F6v9foruOevUfEHBEliNLUUeL36Q==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-postgresql-secret
      namespace: poulet
