apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: poulet
resources:
  - namespace.yaml
  - rbac
  - helm-repository.yaml
  - helm-release.yaml
  - basic-auth-middleware.yaml
  - prometheus-basic-auth-sealed.yaml
  - keycloak-postgresql-secret-sealed.yaml
  - keycloak-secret-sealed.yaml
  - keycloak-ingress.yaml
  - mongo-db-secret-sealed.yaml