apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving

spec:
  config:
    istio:
      local-gateways: |
        - name: knative-local-gateway
          namespace: knative-serving
          service: knative-local-gateway.knative-serving.svc.cluster.local
    domain:
      "knative.apoorva64.com": ""
    network:
      autoTLS: Enabled
      httpProtocol: Enabled
      domainTemplate: "{{.Name}}.{{.Domain}}"
    certmanager:
      issuerRef: |
        kind: ClusterIssuer
        name: letsencrypt-istio-issuer