apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: factorio-dedicated-server
  name: factorio-dedicated-server
  namespace: factorio
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: factorio-dedicated-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.service: factorio-dedicated-server
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - env: []

          image: factoriotools/factorio:1.1.101
          name: factorio-dedicated-server
          ports:
            - containerPort: 34197
              hostPort: 34197
              protocol: UDP
            - containerPort: 27015
              hostPort: 27015
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /factorio
              name: factorio-dedicated-server-claim0
      restartPolicy: Always
      volumes:
        - name: factorio-dedicated-server-claim0
          persistentVolumeClaim:
            claimName: factorio-dedicated-server-claim0
status: {}
