apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwebui-pipelines-deployment
  namespace: open-webui
spec:
  selector:
    matchLabels:
      app: openwebui-pipelines
  replicas: 1
  template:
    metadata:
      labels:
        app: openwebui-pipelines
    spec:
      containers:
        - name: openwebui-pipelines
          image: ghcr.io/open-webui/pipelines:main
          ports:
            - containerPort: 9099
          env:
            # General
            - name: PIPELINES_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openwebui-pipelines-secret
                  key: PIPELINES_API_KEY
            - name: PIPELINES_URLS
              value: https://github.com/open-webui/pipelines/blob/main/examples/filters/langfuse_filter_pipeline.py
            # Langfuse Filter
            - name: LANGFUSE_HOST
              value: "http://langfuse-web.langfuse.svc.cluster.local:3000"
            - name: LANGFUSE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: openwebui-pipelines-secret
                  key: SECRET_KEY
            - name: LANGFUSE_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: openwebui-pipelines-secret
                  key: PUBLIC_KEY
          volumeMounts:
            - name: openwebui-pipelines-volume
              mountPath: /app/pipelines
      volumes:
        - name: openwebui-pipelines-volume
          persistentVolumeClaim:
            claimName: openwebui-pipelines-pvc
