apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: openwebui-pipelines
  name: openwebui-pipelines-pvc
  namespace: open-webui
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
