apiVersion: v1
kind: Service
metadata:
  name: openwebui-pipelines-service
  namespace: open-webui
spec:
  type: ClusterIP # Use LoadBalancer if you're on a cloud that supports it
  selector:
    app: openwebui-pipelines
  ports:
    - protocol: TCP
      port: 9099
      targetPort: 9099
