apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: yvann-poulet
  namespace: poulet
rules:
  - verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
    apiGroups:
      - cert-manager.io
    resources:
      - certificates
      - certificaterequests
      - issuers
  - verbs:
      - update
    apiGroups:
      - cert-manager.io
    resources:
      - certificates/status
  - verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
    apiGroups:
      - acme.cert-manager.io
    resources:
      - challenges
      - orders
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - cert-manager.io
    resources:
      - certificates
      - certificaterequests
      - issuers
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - acme.cert-manager.io
    resources:
      - challenges
      - orders
  - verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
    apiGroups:
      - elasticsearch.k8s.elastic.co
    resources:
      - elasticsearches
  - verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
    apiGroups:
      - autoscaling.k8s.elastic.co
    resources:
      - elasticsearchautoscalers
  - verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
    apiGroups:
      - apm.k8s.elastic.co
    resources:
      - apmservers
  - verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
    apiGroups:
      - kibana.k8s.elastic.co
    resources:
      - kibanas
  - verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
    apiGroups:
      - enterprisesearch.k8s.elastic.co
    resources:
      - enterprisesearches
  - verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
    apiGroups:
      - beat.k8s.elastic.co
    resources:
      - beats
  - verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
    apiGroups:
      - agent.k8s.elastic.co
    resources:
      - agents
  - verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
    apiGroups:
      - maps.k8s.elastic.co
    resources:
      - elasticmapsservers
  - verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
    apiGroups:
      - stackconfigpolicy.k8s.elastic.co
    resources:
      - stackconfigpolicies
  - verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
    apiGroups:
      - logstash.k8s.elastic.co
    resources:
      - logstashes
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - elasticsearch.k8s.elastic.co
    resources:
      - elasticsearches
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - autoscaling.k8s.elastic.co
    resources:
      - elasticsearchautoscalers
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - apm.k8s.elastic.co
    resources:
      - apmservers
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - kibana.k8s.elastic.co
    resources:
      - kibanas
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - enterprisesearch.k8s.elastic.co
    resources:
      - enterprisesearches
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - beat.k8s.elastic.co
    resources:
      - beats
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - agent.k8s.elastic.co
    resources:
      - agents
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - maps.k8s.elastic.co
    resources:
      - elasticmapsservers
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - stackconfigpolicy.k8s.elastic.co
    resources:
      - stackconfigpolicies
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - logstash.k8s.elastic.co
    resources:
      - logstashes
  - verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
    apiGroups:
      - notification.toolkit.fluxcd.io
      - source.toolkit.fluxcd.io
      - helm.toolkit.fluxcd.io
      - image.toolkit.fluxcd.io
      - kustomize.toolkit.fluxcd.io
    resources:
      - '*'
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - notification.toolkit.fluxcd.io
      - source.toolkit.fluxcd.io
      - helm.toolkit.fluxcd.io
      - image.toolkit.fluxcd.io
      - kustomize.toolkit.fluxcd.io
    resources:
      - '*'
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - pods/attach
      - pods/exec
      - pods/portforward
      - pods/proxy
      - secrets
      - services/proxy
  - verbs:
      - impersonate
    apiGroups:
      - ''
    resources:
      - serviceaccounts
  - verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
    apiGroups:
      - ''
    resources:
      - pods
      - pods/attach
      - pods/exec
      - pods/portforward
      - pods/proxy
  - verbs:
      - create
    apiGroups:
      - ''
    resources:
      - pods/eviction
  - verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
    apiGroups:
      - ''
    resources:
      - configmaps
      - events
      - persistentvolumeclaims
      - replicationcontrollers
      - replicationcontrollers/scale
      - secrets
      - serviceaccounts
      - services
      - services/proxy
  - verbs:
      - create
    apiGroups:
      - ''
    resources:
      - serviceaccounts/token
  - verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
    apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - deployments/rollback
      - deployments/scale
      - replicasets
      - replicasets/scale
      - statefulsets
      - statefulsets/scale
  - verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
    apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
  - verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
    apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
  - verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
    apiGroups:
      - extensions
    resources:
      - daemonsets
      - deployments
      - deployments/rollback
      - deployments/scale
      - ingresses
      - networkpolicies
      - replicasets
      - replicasets/scale
      - replicationcontrollers/scale
  - verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
    apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
  - verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
    apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
      - networkpolicies
  - verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - coordination.k8s.io
    resources:
      - leases
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - metrics.k8s.io
    resources:
      - pods
      - nodes
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - configmaps
      - endpoints
      - persistentvolumeclaims
      - persistentvolumeclaims/status
      - pods
      - replicationcontrollers
      - replicationcontrollers/scale
      - serviceaccounts
      - services
      - services/status
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - bindings
      - events
      - limitranges
      - namespaces/status
      - pods/log
      - pods/status
      - replicationcontrollers/status
      - resourcequotas
      - resourcequotas/status
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - namespaces
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - apps
    resources:
      - controllerrevisions
      - daemonsets
      - daemonsets/status
      - deployments
      - deployments/scale
      - deployments/status
      - replicasets
      - replicasets/scale
      - replicasets/status
      - statefulsets
      - statefulsets/scale
      - statefulsets/status
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
      - horizontalpodautoscalers/status
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - batch
    resources:
      - cronjobs
      - cronjobs/status
      - jobs
      - jobs/status
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - extensions
    resources:
      - daemonsets
      - daemonsets/status
      - deployments
      - deployments/scale
      - deployments/status
      - ingresses
      - ingresses/status
      - networkpolicies
      - replicasets
      - replicasets/scale
      - replicasets/status
      - replicationcontrollers/scale
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
      - poddisruptionbudgets/status
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
      - ingresses/status
      - networkpolicies
  - verbs:
      - create
    apiGroups:
      - authorization.k8s.io
    resources:
      - localsubjectaccessreviews
  - verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
      - roles