apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: yvann
  namespace: poulet
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name:  yvann-poulet
subjects:
  - kind: User
    name: yvann.ponce@gmail.com
    apiGroup: rbac.authorization.k8s.io
  - kind: User
    name: apoorvaappadoo@gmail.com
    apiGroup: rbac.authorization.k8s.io