apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins-operator
  namespace: jenkins
spec:
  interval: 60m
  chart:
    spec:
      chart: jenkins-operator
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: flux-system
      interval: 12h
  values:
    jenkins:
      namespace: jenkins
      plugins:
        - name: saml
          version: 689.v731678c3e0eb_
        - name: role-strategy
          version: 3.0.2