apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jenkins
  namespace: flux-system
spec:
  interval: 60m0s
  url: https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/chart