apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redirect-rtf
  namespace: react-flight-tracker
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: react-flight-tracker-redirect-to-flight-tracker
spec:
  rules:
    - host: rtf.apoorva64.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: noop
                port:
                  number: 80
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-flight-tracker
  namespace: react-flight-tracker
spec:
  redirectRegex:
    regex: "^(http://)(.*)"
    replacement: "https://react-flight-tracker.apoorva64.com/"
    permanent: true
