apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kuberay-operator
  namespace: kube-ray
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 60m
  chart:
    spec:
      chart: kuberay-operator
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: kuberay
        namespace: kube-ray
      interval: 12h
  values:
#    image:
#      repository: apoorva64/kuberay-operator
#      tag: latest-arm64
#      pullPolicy: IfNotPresent
#
    nodeSelector:
      kubernetes.io/arch: amd64