apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: ollama-node-apoorva3
  namespace: flux-system
spec:
  interval: 5m
  path: ./manifests
  prune: true
  targetNamespace: ollama-node-apoorva3
  sourceRef:
    kind: GitRepository
    name: llama-bot