apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kepler
  namespace: monitoring
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 60m
  chart:
    spec:
      chart: kepler
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: kepler
        namespace: monitoring
      interval: 12h
