---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: langfuse
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBaewOOy5Ne0KwLeQd2CHkWbcfPYY1m032vaxLBpAlsAshePbhSRRdkrNQhkB7Jm8EsthVl968QAw+hkB0knwfPY9E35z5AGsSbOOV0rPEwsrs+Be87xDiSjpzoMpp+koH1/orYWGxcBgkGBf0T4XdDZzaZEy7sjAB/APiikfq1NqZbef9fIgNjzX1OzvLx8cInsjksySEFtWVM8qubhpRfGf33+TDgBY29VSwAfFK9fX9gyrkfwyIIA5vZkyHt6XSRCCTUOAil1EYlOSdYDfVDJzkRRbNKWhngoI+PvCUuOKNvJPeYSVtLCYR+7mviEqg4bf+YuIRR+b/IHmEcfiikvBzokNU+uhn+CVGWlDeRrBJSng/5TkJdg/xbSFDTXAMPVrKyseK+s/X2yuHnUnXqiNGlenYg2QybjnToMyBOpKvP7IxCj8DykvK5FsSd3HzYZMrHNQQsVvqdRRqrWooruKzXFwTovHzw6jwsnz+a0hEE5DfOENIw00lF2pCJaiLnT1c4YSdlEonRrK70VUxr0CaRjJL285pExSLh6hmnCxkdO4rvyu1OdJHi2w8pFk8c+eyVYiTeHyu8iwabsg7hybp+9RegxWSyiIVk2hqyvUEtGH4kXHbztphVn/xiFtrgmBenMGLMgCgFejiSQCbv4WTD2+tfMvgPy681LMxX2Xbc1AiWQt8kVU87wim/tlVA/fhIJFtPUD45Fdq/5I6blkHwHA==
    ACCESS_SECRET_KEY: AgA4PJYGk6rHnA1c6xGgW3w3qWe1FC6DJTlIBQwUVRAuzrEWj29cmybQsuFMs/4c47kleSGut5nwtRpkyHsKVUPJrXoXEukRisvs4nGu7tp/1A4xSovMGO8XzdKsaC2FK5Ddg/zqKWAM/Ur7f3DjyitNs/6ThXACuvmddKyVUpR7EvaD8BgXTEWmGXfjHmEStJ9u1B71+BYLccEnJDBtrh2ci9oQTMh3DXVJvWxkFm8adrQKGYvVw6hlE5v0wcDUfAeD3zxMP5SXJb9nAtHSyytEhDBXqig5wfbAALRhiajV8DMb4dQLLl7VL7TgAhZzbmZ/RMcgYti2pIGuzWqcWToTPdHQcFgkCvau0spoQAEqleOJhqZLIquFhQ3K/8P8M9yjvkHjISLm8aoYLGiuDUQPjIfOqy049ofLXo6Ozj0fL77/AnIf1yDkGB49F52SDyCScmKMKIxulUO5LbvsrGESSqmULywWbC0AIKgUnixlAsElNPK84Kl8zdXGfBZQ4eJ5NA+ftQiPsNjPzeyNLfFYm+GIRskxPYDPXbFraGGRUHOYVLe0+3rH23a6JwHEUqsCVYnaj+Xt0K/6r6rfSJvxa1ncCfj2pO9W+kbYAee844QIrMHCzmlcNM9oGIiSdtKIEQqkS0dNEr55pstymSukg11ClsatndRmhab12v4xsYeES52PzIrEpOEzCTLQ2WoB10M4cgw227zHL/O09Pvs/HzC9TGstrkmeNE+P5J2hw0sY9wiXMhT
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: langfuse
    type: Opaque
