apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: langfuse-db
  namespace: langfuse
spec:
  instances: 3
  storage:
    storageClass: local-path
    size: 5Gi
  backup:
    barmanObjectStore:
      destinationPath: "s3://backup-cloudnative-pg/langfuse/"
      s3Credentials:
        accessKeyId:
          name: minio-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: minio-creds
          key: ACCESS_SECRET_KEY
      endpointURL: "http://minio.ozeliurs.com:9000"
