apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ray-gpu-cluster
  namespace: kube-ray
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 60m
  chart:
    spec:
      chart: ray-cluster
      version: "0.6.0"
      sourceRef:
        kind: HelmRepository
        name: kuberay
        namespace: kube-ray
      interval: 12h
  values:
    worker:
      runtimeClass: nvidia
      nodeSelector:
        kubernetes.io/arch: amd64
      replicas: 1
      resources: { }
      ports:
        - containerPort: 6379
          name: gcs-server
        - containerPort: 8265
          name: dashboard
        - containerPort: 8000
          name: serve
        - containerPort: 10001
          name: client
        - containerPort: 8080
          name: metrics
    head:
      runtimeClass: nvidia
      nodeSelector:
        kubernetes.io/arch: amd64
      resources: { }

      ports:
        - containerPort: 6379
          name: gcs-server
        - containerPort: 8265
          name: dashboard
        - containerPort: 8000
          name: serve
        - containerPort: 10001
          name: client
        - containerPort: 8080
          name: metrics