apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
  namespace: observability
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 60m
  chart:
    spec:
      chart: tempo
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: observability
      interval: 12h
  values:
    tempo:
      mode: single-binary
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 1
          memory: 1Gi

      storage:
        trace:
          backend: local
          local:
            path: /var/tempo/traces

      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: "0.0.0.0:4317"
            http:
              endpoint: "0.0.0.0:4318"

      metricsGenerator:
        enabled: true
        remoteWriteUrl: "http://prometheus:9090/api/v1/write"

    persistence:
      enabled: true
      size: 10Gi
      storageClass: local-path
