apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: simple-ollama-operator-manager
  namespace: ollama-node-nino4
spec:
  interval: 5m
  path: ./config/manager
  prune: true
  targetNamespace: ollama-node-nino4
  sourceRef:
    kind: GitRepository
    name: simple-ollama-operator
    namespace: flux-system
  patches:
    # Add WATCH_NAMESPACE env var
    # Replace OLLAMA_URL env var
    - patch: |-
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                  fieldPath: metadata.namespace
        - op: replace
          path: /spec/template/spec/containers/0/env/0/value
          value: http://ollama-service.ollama.svc.cluster.local:8080

      target:
        kind: Deployment

