apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: simple-ollama-operator-rbac
  namespace: ollama-node-nino4
spec:
  interval: 5m
  path: ./config/rbac
  prune: true
  targetNamespace: ollama-node-nino4
  sourceRef:
    kind: GitRepository
    name: simple-ollama-operator
    namespace: flux-system