apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo
resources:
  - ../../base/podinfo
namePrefix: prod-
patches:
  - target:
      kind: HelmRelease
      name: podinfo
    path: release-patch.yaml