apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak-postgres-ha
  namespace: keycloak
spec:
  interval: 60m
  chart:
    spec:
      chart: postgresql-ha
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: postgresql
        namespace: artifactory
      interval: 24h
  values:
    global:
      postgresql:
        auth:
          username: "artifactory"
          password: "artifactory"
          database: "artifactory"