apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: artifactory-postgres
  namespace: artifactory
spec:
  interval: 60m
  chart:
    spec:
      chart: postgresql
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: artifactory
      interval: 24h
  values:
    global:
      postgresql:
        auth:
          username: "artifactory"
          password: "artifactory"
          database: "artifactory"