apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo
resources:
  - namespace.yaml
  - repository.yaml
  - role.yaml
  - service-account.yaml
  - role-binding.yaml
  - release.yaml
