# role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: podinfo
  namespace: podinfo
rules:
  - apiGroups: [ "" ]
    resources: [ "pods","services","deployments", "secrets", "ingresses" ]
    verbs: [ "get", "watch", "list" ]