apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prod-db
  namespace: spos-prod
spec:
  interval: 60m
  chart:
    spec:
      chart: mongodb
      version: "15.6.26"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 24h
  values:
    image:
      registry: docker.io
      repository: arm64v8/mongo
      tag: 7.0.14
    auth:
      enabled: false
    persistence:
      size: 1Gi
    nodeSelector:
      kubernetes.io/hostname: node-apoorva