apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor-database-redis
  namespace: harbor
spec:
  interval: 60m
  chart:
    spec:
      chart: redis
      version: "18.19.2"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 24h
  values:
    global:
      storageClass: longhorn-single-replica

