apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak-postgres-ha
  namespace: keycloak
spec:
  interval: 60m
  chart:
    spec:
      chart: postgresql-ha
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: keycloak
      interval: 24h
  values:
    pgpool:
      replicaCount: 2
    persistence:
      storageClass: longhorn-single-replica
      size: 8Gi
