apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak-postgres-ha
  namespace: keycloak
spec:
  interval: 60m
  chart:
    spec:
      chart: postgresql-ha
      version: "13.6.1"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: keycloak
      interval: 24h
  values:
    witness:
      create: true
      replicaCount: 3
    pgpool:
      replicaCount: 1
    persistence:
      storageClass: longhorn-single-replica
      size: 8Gi
    postgresql:
      syncReplication: true
      syncReplicationMode: FIRST
      nodeSelector:
        kubernetes.io/arch: arm64
    global:
      postgresql:
        existingSecret: keycloak-postgres-ha-postgresql-ha-postgresql
      pgpool:
        existingSecret: keycloak-postgres-ha-postgresql-ha-pgpool
