apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: devops-tools
spec:
  interval: 60m
  chart:
    spec:
      chart: weave-gitops
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system
      interval: 24h
  values:
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 1
        memory: 512Mi
    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
#    adminUser:
#      create: true
#      createClusterRole: true
#      passwordHash: $2a$10$P.vkIIrdUOfupHZJRecCu.c7V9S5dDF88.3z12H5BFDBHB4s7qp2i

    additionalArgs:
      - --auth-methods=oidc