apiVersion: v1
data:
  clientID: <base64 encoded clientID>
  clientSecret: <base64 encoded clientSecret>
  issuerURL: <base64 encoded issuerURL>
  redirectURL: <base64 encoded redirectURL>
kind: Secret
metadata:
  name: oidc-auth
  namespace: devops-tools