apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: main-keycloak
  namespace: keycloak
spec:
  additionalOptions:
    - name: proxy
      value: edge
  db:
    host: mariadb-galera
    passwordSecret:
      key: mariadb-password
      name: mariadb-galera
    usernameSecret:
      key: username
      name: db-username
    vendor: mariadb
  hostname:
    hostname: keycloak.auth.apoorva64.com
  image: quay.io/keycloak/keycloak:22.0.5
  instances: 3
  transaction:
    xaEnabled: true
