apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: main-keycloak
  namespace: keycloak
spec:
  instances: 3
  db:
    vendor: mariadb
    host: mariadb-galera
    database: keycloak
    usernameSecret:
      name: db-username
      key: username
    passwordSecret:
      name: mariadb-galera
      key: mariadb-password
  hostname:
    hostname: keycloak.auth.apoorva64.com
