apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: main-keycloak
  namespace: keycloak
spec:
  instances: 3
  image: quay.io/keycloak/keycloak:latest
  db:
    usernameSecret:
      name: db-username
      key: username
    passwordSecret:
      name: mariadb-galera
      key: mariadb-password

  transaction:
    xaEnabled: true
  hostname:
    hostname: keycloak.auth.apoorva64.com
  additionalOptions:
    - name: "proxy"
      value: "edge"
