apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  additionalOptions:
    - name: proxy
      value: edge
  db:
    host: keycloak-postgres-ha-postgresql-ha-pgpool
    passwordSecret:
      key: password
      name: keycloak-postgres-ha-postgresql-ha-postgresql
    usernameSecret:
      key: username
      name: db-username
    vendor: mysql
    port: 4000
  hostname:
    hostname: keycloak.auth.apoorva64.com
  instances: 1
