apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  db:
    host: keycloak-postgres-ha-postgresql-ha-pgpool
    passwordSecret:
      key: password
      name: keycloak-postgres-ha-postgresql-ha-postgresql
    usernameSecret:
      key: username
      name: db-username
    vendor: postgres
    database: postgres
  transaction:
    xaEnabled: true
  hostname:
    hostname: keycloak.auth.apoorva64.com
  instances: 3
  ingress:
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.tls: "true"
  additionalOptions:
    - name: proxy-address-forwarding
      value: "true"