apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  db:
    host: keycloak-postgres-ha-postgresql-ha-pgpool
    passwordSecret:
      key: password
      name: keycloak-postgres-ha-postgresql-ha-postgresql
    usernameSecret:
      key: username
      name: db-username
    vendor: postgres
    database: postgres
  hostname:
    hostname: keycloak.auth.apoorva64.com
  instances: 3
  ingress:
    enabled: false
  transaction:
    xaEnabled: true
  additionalOptions:
    - name: proxy-address-forwarding
      value: "true"
    - name: proxy
      value: edge