apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db
  namespace: keycloak
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.2
  storage:
    storageClass: local-path
    size: 5Gi
  bootstrap:
    pg_basebackup:
      source: source-db
  externalClusters:
    - name: source-db
      connectionParameters:
        host: keycloak-postgres-ha-postgresql-ha-pgpool
        user: postgres
      password:
        name: keycloak-postgres-ha-postgresql-ha-postgresql
        key: password
#  backup:
#    barmanObjectStore:
#      destinationPath: "s3://backup-cloudnative-pg/keycloak/"
#      s3Credentials:
#        accessKeyId:
#          name: minio-creds
#          key: ACCESS_KEY_ID
#        secretAccessKey:
#          name: minio-creds
#          key: ACCESS_SECRET_KEY
#      endpointURL: "http://minio.ozeliurs.com:9000"
