apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ../../base/youtube-analyzer
namePrefix: prod-

patches:
  - target:
      kind: Kustomization
      name: youtube-analyzer
    path: kustomize-patch.yaml