apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb-community-operator
  namespace: mongodb-community-operator
spec:
  interval: 60m
  chart:
    spec:
      chart: community-operator
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: mongodb
        namespace: mongodb-community-operator
      interval: 24h
  values:
    operator:
      watchNamespace: "*"